"""Velocity Demo Knowledge Base — authored SOP corpus.

Original, luxury-standard hospitality SOPs spanning all core departments. Written
to feel authentic to a hotel executive while containing no proprietary or
copyrighted material — every property replaces this with its own SOPs at pilot time
(same schema, no code change). This is the "quality core"; the schema and loader
scale to hundreds of SOPs as the content pipeline grows.

Grounded in real operational patterns observed across luxury resort and cruise
operations (execution gaps between systems and people, inventory leakage, onboarding
delays, handover failures, guest-recovery timing) — the problems Velocity exists to
close.
"""
from __future__ import annotations

from .schema import SOP

# Authored as plain dicts for readability; SOP.from_dict validates them.
_RAW: list[dict] = [
    # ===================== FRONT OFFICE =====================
    {
        "sop_id": "FO-101", "department": "Front Office",
        "title": "VIP Arrival & Check-In",
        "purpose": "Deliver a flawless, personalised arrival for VIP and repeat guests so the first five minutes set the tone for the entire stay.",
        "business_outcome": "Higher guest-satisfaction and loyalty conversion; fewer service-recovery incidents; stronger repeat-booking rate.",
        "scope": "All guests flagged VIP, returning, or on a suite/villa reservation, from lobby arrival to in-room orientation.",
        "roles_responsible": ["Front Office Manager", "Guest Relations", "Duty Manager", "Bell Desk"],
        "required_systems": ["PMS", "Guest Profile / CRM", "Messaging"],
        "preconditions": ["Arrivals list pulled and VIP flags confirmed 24h prior", "Room pre-blocked and inspected", "Welcome amenity ordered"],
        "procedure": [
            "Confirm the VIP arrivals list at the morning briefing and assign a named host to each VIP.",
            "Pre-block and personally inspect the room; verify amenity, preferences (pillow, minibar, floor) from the guest profile.",
            "Greet by name within 10 seconds of lobby arrival; offer a seated or walking check-in, never a queue.",
            "Complete registration on a tablet at the guest's side; verify ID and payment discreetly.",
            "Escort to the room, orient to amenities, and confirm the departure date and any booked experiences.",
            "Log arrival completion and any live preferences back into the guest profile for the whole property to see.",
        ],
        "decision_tree": [
            {"condition": "the pre-blocked room is not ready at arrival", "action": "offer the lounge with a welcome drink, upgrade if inventory allows, and give a firm ready-time owned by the Duty Manager"},
            {"condition": "the guest is a returning VIP with a logged complaint from a prior stay", "action": "the Front Office Manager proactively acknowledges it at arrival and confirms it is resolved"},
        ],
        "escalation_rules": [
            "Any VIP arrival friction (no room, billing dispute, missed preference) escalates to the Duty Manager immediately.",
            "Suite/villa or repeat-guest complaints escalate to the GM on duty within 15 minutes.",
        ],
        "quality_standards": [
            "Guest greeted by name within 10 seconds; zero queue for VIPs.",
            "Room personalised to at least two profile preferences.",
            "Every preference observed at arrival written back to the profile the same shift.",
        ],
        "kpis": ["VIP check-in time < 4 min", "Pre-blocked-room readiness rate", "Repeat-guest satisfaction score"],
        "common_mistakes": [
            "Treating a VIP arrival as a standard check-in because the flag was missed at briefing.",
            "Capturing preferences on paper that never reach the guest profile — so the next shift repeats the mistake.",
        ],
        "ai_summary": "Named-host, no-queue, personalised VIP arrival; preferences captured back to the profile; any friction escalates to the Duty Manager.",
        "related_sops": ["GX-201", "HK-301", "RES-701"],
        "search_keywords": ["vip", "check-in", "arrival", "welcome", "suite", "returning guest", "escort", "upgrade"],
        "quiz": [
            {"question": "Within how many seconds should a VIP be greeted by name?", "answer": "Within 10 seconds of lobby arrival."},
            {"question": "Where must preferences observed at arrival be recorded?", "answer": "Written back into the guest profile the same shift."},
        ],
        "follow_up_actions": ["Notify Housekeeping of any live room preference", "Confirm booked experiences with Guest Experience", "Set a departure-eve check-in reminder"],
        "category_tags": ["arrival", "vip", "loyalty"], "priority": "critical",
    },
    {
        "sop_id": "FO-108", "department": "Front Office",
        "title": "Late Check-Out Request",
        "purpose": "Handle late check-out requests consistently, protecting housekeeping turnaround and same-day arrivals while maximising guest goodwill and ancillary revenue.",
        "business_outcome": "Balanced room-readiness for arrivals with guest satisfaction; incremental late-check-out revenue where inventory allows.",
        "scope": "All in-house guests requesting a departure later than the standard check-out time.",
        "roles_responsible": ["Front Office", "Duty Manager", "Housekeeping Coordinator"],
        "required_systems": ["PMS", "Housekeeping board"],
        "preconditions": ["Same-day arrivals and occupancy checked", "Loyalty tier and rate plan visible"],
        "procedure": [
            "Check same-day arrivals and occupancy for the room type before answering.",
            "Grant complimentary late check-out to top loyalty tiers where inventory allows.",
            "For others, offer a paid late check-out or half-day rate, or a firm alternative time.",
            "Update the PMS departure time and notify the Housekeeping Coordinator so the board re-sequences.",
        ],
        "decision_tree": [
            {"condition": "the room type is sold out for same-day arrival", "action": "offer luggage storage and lounge access instead of extending, and set a firm vacate time"},
            {"condition": "the guest is a top-tier loyalty member and inventory allows", "action": "grant complimentary late check-out and log the gesture on the profile"},
        ],
        "escalation_rules": ["Disputes over a charged late check-out escalate to the Duty Manager, who owns the final call."],
        "quality_standards": ["Every late check-out reflected in the PMS and on the housekeeping board before the guest leaves the desk."],
        "kpis": ["Late-check-out revenue capture", "Arrival room-readiness rate", "Related complaint rate"],
        "common_mistakes": ["Granting late check-out verbally without updating housekeeping, causing a room-not-ready failure for an arriving guest."],
        "ai_summary": "Check arrivals/occupancy first; comp for top tiers when inventory allows, else offer paid/alternative; always update PMS + housekeeping.",
        "related_sops": ["HK-301", "FO-101"],
        "search_keywords": ["late check-out", "checkout", "extend", "departure", "half-day rate"],
        "quiz": [{"question": "What must be updated the moment a late check-out is granted?", "answer": "The PMS departure time and the housekeeping board."}],
        "follow_up_actions": ["Notify Housekeeping Coordinator", "Add any charge to the folio"],
        "category_tags": ["departure", "revenue"], "priority": "high",
    },
    # ===================== FOOD & BEVERAGE =====================
    {
        "sop_id": "FB-210", "department": "Food & Beverage",
        "title": "Cocktail Preparation & Pour Consistency",
        "purpose": "Guarantee every cocktail is made to brand spec so guests get identical quality across bars and shifts, and beverage cost stays controlled.",
        "business_outcome": "Consistent guest experience; beverage pour cost held to target; reduced inventory leakage from over-pouring.",
        "scope": "All bars and service points preparing cocktails and premium spirits.",
        "roles_responsible": ["Bar Manager", "Bartender", "F&B Manager"],
        "required_systems": ["POS / Micros", "Inventory / stock control"],
        "preconditions": ["Recipe cards available at each station", "Jiggers and calibrated pourers in use"],
        "procedure": [
            "Make every cocktail to the printed recipe card; measure spirits with a jigger — never free-pour by eye.",
            "Example — Mojito: 50ml white rum, 8 mint leaves, 25ml fresh lime, 2 tsp sugar, top with soda.",
            "Ring every drink into the POS before serving; comps and spills are logged, not absorbed.",
            "For a premium-spirit upgrade, confirm the brand with the guest and ring the correct price tier.",
            "Reconcile high-value spirits against POS at shift close; variance over 5% is escalated.",
        ],
        "decision_tree": [
            {"condition": "measured pour cost variance exceeds 5% at shift close", "action": "the Bar Manager investigates unlogged comps/spills or over-pouring before the next service"},
            {"condition": "a guest requests a premium-spirit upgrade", "action": "confirm the brand, ring the higher price tier, and pour to the same measured spec"},
        ],
        "escalation_rules": ["Unlogged variance over 5% escalates to the Bar Manager same shift; repeated variance escalates to F&B Manager."],
        "quality_standards": ["Target pour cost 18–22%.", "100% of drinks measured with a jigger.", "Every drink ringed into POS before serving."],
        "kpis": ["Beverage pour cost %", "Spirit variance %", "Comp/spill log completeness"],
        "common_mistakes": ["Free-pouring during a rush (destroys cost control and consistency).", "Serving before ringing into POS, so inventory never reconciles."],
        "ai_summary": "Jigger every pour to recipe spec, ring into POS before serving, log comps/spills, reconcile spirits at shift close; >5% variance escalates.",
        "related_sops": ["FB-214", "FIN-610"],
        "search_keywords": ["cocktail", "mojito", "pour cost", "jigger", "premium spirit", "upgrade", "bar", "variance", "micros"],
        "quiz": [
            {"question": "How much white rum goes in a Mojito?", "answer": "50ml, measured with a jigger."},
            {"question": "What is the target beverage pour cost?", "answer": "18–22%."},
        ],
        "follow_up_actions": ["Log any comp/spill", "Flag variance > 5% to the Bar Manager"],
        "category_tags": ["beverage", "cost-control", "consistency"], "priority": "high",
    },
    {
        "sop_id": "FB-214", "department": "Food & Beverage",
        "title": "Restaurant Reservation Conflict",
        "purpose": "Resolve double-booked or over-capacity reservations gracefully while protecting the guest experience and table yield.",
        "business_outcome": "Fewer seating failures and complaints; protected covers and F&B revenue; smoother service flow.",
        "scope": "All restaurant and in-villa dining reservations across channels.",
        "roles_responsible": ["Restaurant Manager", "Host", "F&B Manager"],
        "required_systems": ["Reservation / table-management", "PMS", "Messaging"],
        "preconditions": ["Table plan current", "Pacing and turn-times configured"],
        "procedure": [
            "Confirm the conflict against the live table plan and identify the earliest true availability.",
            "Contact the affected guest proactively — never let them arrive to a problem.",
            "Offer the nearest slot, a preferred alternative venue, or a complimentary aperitif while a table is cleared.",
            "Rebalance the pacing so the recovery doesn't cascade into later bookings.",
        ],
        "decision_tree": [
            {"condition": "no table will free within 20 minutes", "action": "offer an alternative outlet or in-villa dining with a goodwill gesture, owned by the Restaurant Manager"},
            {"condition": "the guest is a VIP or celebrating an occasion", "action": "escalate to the Restaurant Manager to personally reseat and add a recognition touch"},
        ],
        "escalation_rules": ["Any reseat delay beyond 20 minutes or a VIP/occasion conflict escalates to the Restaurant Manager."],
        "quality_standards": ["Guests contacted before arrival whenever a conflict is known in advance."],
        "kpis": ["Seating-failure rate", "Reservation-related complaints", "Cover yield"],
        "common_mistakes": ["Waiting for the guest to arrive before addressing a known conflict."],
        "ai_summary": "Verify against the live table plan, contact the guest before arrival, offer nearest slot/alternative/aperitif, rebalance pacing; VIP/occasion escalates.",
        "related_sops": ["FO-101", "EVT-810"],
        "search_keywords": ["reservation", "restaurant", "double booking", "table", "conflict", "dining", "seating"],
        "quiz": [{"question": "When should a guest be contacted about a known reservation conflict?", "answer": "Proactively, before they arrive."}],
        "follow_up_actions": ["Log the recovery gesture", "Review pacing for the affected service"],
        "category_tags": ["dining", "recovery"], "priority": "standard",
    },
    # ===================== HOUSEKEEPING =====================
    {
        "sop_id": "HK-301", "department": "Housekeeping",
        "title": "Room Readiness & Turnaround Handover",
        "purpose": "Get departed rooms inspected and released to Front Office on time so arrivals never wait, and standards never slip under pressure.",
        "business_outcome": "Higher on-time room-ready rate; fewer arrival delays; protected cleanliness scores.",
        "scope": "All departure and stay-over rooms from cleaning to Front Office release.",
        "roles_responsible": ["Executive Housekeeper", "Floor Supervisor", "Room Attendant", "Housekeeping Coordinator"],
        "required_systems": ["Housekeeping board", "PMS"],
        "preconditions": ["Arrivals priority list received from Front Office", "Attendant boards assigned"],
        "procedure": [
            "Sequence cleaning by arrivals priority — pre-blocked VIP and early-arrival rooms first.",
            "Clean to the room checklist; attendant self-checks before calling for inspection.",
            "Floor Supervisor inspects and only then releases the room as ready in the system.",
            "Coordinator updates the board and notifies Front Office the moment a priority room is ready.",
        ],
        "decision_tree": [
            {"condition": "an arriving guest is waiting on a specific room", "action": "the Floor Supervisor fast-tracks inspection and gives Front Office a firm ready-time"},
            {"condition": "a maintenance defect is found during cleaning", "action": "raise a work order, hold the room, and offer an equivalent alternative to Front Office"},
        ],
        "escalation_rules": ["Any room that will miss an arrival's ready-time escalates to the Executive Housekeeper and Duty Manager."],
        "quality_standards": ["No room released 'ready' without supervisor inspection.", "Priority rooms updated in the system in real time, not batched."],
        "kpis": ["On-time room-ready rate", "Inspection pass rate", "Arrival wait time"],
        "common_mistakes": ["Marking a room ready before inspection.", "Cleaning in room-number order instead of by arrivals priority."],
        "ai_summary": "Clean by arrivals priority, inspect before release, update the board in real time; defects raise a work order and hold the room.",
        "related_sops": ["FO-101", "MN-401"],
        "search_keywords": ["housekeeping", "room ready", "turnaround", "handover", "inspection", "clean", "delay"],
        "quiz": [{"question": "Who may release a room as 'ready'?", "answer": "Only after a Floor Supervisor inspection."}],
        "follow_up_actions": ["Notify Front Office on priority-room release", "Raise a work order for any defect"],
        "category_tags": ["rooms", "handover"], "priority": "critical",
    },
    # ===================== HUMAN RESOURCES =====================
    {
        "sop_id": "HR-501", "department": "Human Resources",
        "title": "New-Hire Preboarding & Work-Permit Compliance",
        "purpose": "Ensure every new hire arrives fully documented, permit-compliant, and trained on day one — so onboarding never delays a department.",
        "business_outcome": "Faster time-to-productivity; zero compliance gaps on permits/visas; consistent day-one readiness.",
        "scope": "All new hires from offer acceptance to end of probation, across departments.",
        "roles_responsible": ["HR Manager", "HR Officer", "Department Head"],
        "required_systems": ["HRIS", "Document store", "Training LMS"],
        "preconditions": ["Signed offer on file", "Role and start date confirmed"],
        "procedure": [
            "Determine the required documents for the role: passport, work permit, signed contract, tax form — F&B and kitchen roles also require a valid food-handler certificate before their first shift.",
            "Collect and verify each document; flag anything missing against the start date.",
            "Check work-permit/visa validity through the contract period; begin renewal for any permit expiring within 30 days of the start date.",
            "Assign the role-specific training plan and department orientation before day one.",
            "Produce a readiness digest per hire for the Department Head and confirm day-one logistics (uniform, access, payroll setup).",
        ],
        "decision_tree": [
            {"condition": "a required document is missing close to the start date", "action": "HR requests it from the hire and, with approval, holds the start until compliant"},
            {"condition": "a work permit expires within 30 days of the start date", "action": "escalate and begin renewal before onboarding completes"},
        ],
        "escalation_rules": ["Any missing document or near-expiry permit escalates to the HR Manager and requires human approval before onboarding proceeds."],
        "quality_standards": ["No hire starts a shift without required documents.", "Permit renewals initiated ahead of expiry, never after."],
        "kpis": ["Day-one readiness rate", "Onboarding cycle time", "Permit-compliance rate"],
        "common_mistakes": ["Discovering a missing permit on the start date.", "Assigning generic training instead of the role-specific plan."],
        "ai_summary": "Determine role documents, verify and flag gaps, renew permits expiring within 30 days of start, assign role training, produce a per-hire readiness digest; gaps require approval.",
        "related_sops": ["HR-505", "SEC-901"],
        "search_keywords": ["onboarding", "preboarding", "work permit", "visa", "documents", "new hire", "food handler", "training", "probation", "compliance"],
        "quiz": [
            {"question": "Which documents are required before a new hire's first shift?", "answer": "Passport, work permit, signed contract, tax form — plus a food-handler certificate for F&B/kitchen roles."},
            {"question": "When must a permit renewal begin?", "answer": "For any permit expiring within 30 days of the start date."},
        ],
        "follow_up_actions": ["Request missing documents", "Escalate near-expiry permits for approval", "Assign training plan"],
        "category_tags": ["onboarding", "compliance"], "priority": "critical",
    },
    {
        "sop_id": "HR-505", "department": "Human Resources",
        "title": "Uniform Issue & Grooming Standards",
        "purpose": "Issue correct, well-fitted uniforms and set grooming standards so every new hire presents to brand from their first shift.",
        "business_outcome": "Consistent brand presentation; fewer first-week issues; faster floor-readiness.",
        "scope": "All new and transferring staff requiring uniform issue.",
        "roles_responsible": ["HR Officer", "Uniform Room", "Department Head"],
        "required_systems": ["HRIS", "Uniform inventory"],
        "preconditions": ["Sizes captured at preboarding", "Role dress code confirmed"],
        "procedure": [
            "Capture uniform sizes during preboarding, not on day one.",
            "Pre-pick the correct uniform set and grooming kit per role and shift.",
            "Fit-check on issue; exchange immediately if fit or condition is off.",
            "Brief grooming standards and log the issued items against the employee record.",
        ],
        "decision_tree": [
            {"condition": "the correct size is out of stock", "action": "issue a temporary set and raise a replenishment order with a firm ETA"},
        ],
        "escalation_rules": ["Repeated stockouts escalate to HR Manager and Procurement."],
        "quality_standards": ["No staff on the floor out of grooming/uniform standard."],
        "kpis": ["Day-one uniform-ready rate", "Uniform stockout rate"],
        "common_mistakes": ["Capturing sizes on day one, causing a floor delay."],
        "ai_summary": "Capture sizes at preboarding, pre-pick per role, fit-check on issue, brief grooming, log items; stockouts get a temporary set + replenishment.",
        "related_sops": ["HR-501"],
        "search_keywords": ["uniform", "grooming", "dress code", "issue", "fitting", "new hire"],
        "quiz": [{"question": "When should uniform sizes be captured?", "answer": "During preboarding, not on day one."}],
        "follow_up_actions": ["Raise replenishment for any stockout"],
        "category_tags": ["onboarding", "brand-standard"], "priority": "standard",
    },
    # ===================== MAINTENANCE =====================
    {
        "sop_id": "MN-401", "department": "Maintenance",
        "title": "Work-Order Triage & SLA Routing",
        "purpose": "Triage maintenance requests by safety and guest impact and route them to the right trade with a clear SLA, so nothing critical waits.",
        "business_outcome": "Faster resolution of guest-impacting and safety defects; fewer rooms out of order; auditable accountability.",
        "scope": "All maintenance requests from guests, staff, and inspections.",
        "roles_responsible": ["Chief Engineer", "Maintenance Coordinator", "Duty Manager"],
        "required_systems": ["Work-order / CMMS", "PMS"],
        "preconditions": ["Trades and on-call rota configured", "Priority definitions published"],
        "procedure": [
            "Classify each request: safety-critical, guest-impacting, or routine.",
            "Assign priority and SLA: safety-critical immediate; guest-impacting same day; routine scheduled.",
            "Route to the correct trade with the location, description, and any guest context.",
            "For a guest-occupied or arrival room, coordinate access with Housekeeping/Front Office and confirm completion.",
        ],
        "decision_tree": [
            {"condition": "the defect is safety-critical (electrical, gas, fire, flood, lock)", "action": "dispatch immediately, isolate the hazard, and notify the Duty Manager"},
            {"condition": "the defect is in an arrival room", "action": "hold the room, notify Front Office, and offer an equivalent alternative until cleared"},
        ],
        "escalation_rules": ["Any safety-critical item or a missed SLA escalates to the Chief Engineer and Duty Manager."],
        "quality_standards": ["Safety-critical acknowledged immediately.", "Every work order closed with a completion note."],
        "kpis": ["Mean time to resolve by priority", "SLA adherence", "Rooms out-of-order duration"],
        "common_mistakes": ["Queuing a safety defect behind routine tickets.", "Closing a work order without confirming the fix with the room owner."],
        "ai_summary": "Classify by safety/guest impact, assign SLA, route to the trade with context; safety-critical dispatches immediately; arrival-room defects hold the room.",
        "related_sops": ["HK-301", "ENG-410", "SEC-901"],
        "search_keywords": ["work order", "maintenance", "triage", "sla", "repair", "safety", "escalation", "out of order"],
        "quiz": [{"question": "What SLA does a safety-critical defect get?", "answer": "Immediate dispatch, with the hazard isolated and the Duty Manager notified."}],
        "follow_up_actions": ["Notify Front Office for occupied/arrival rooms", "Close with a completion note"],
        "category_tags": ["maintenance", "safety", "sla"], "priority": "critical",
    },
    # ===================== EXECUTIVE OPERATIONS =====================
    {
        "sop_id": "EX-601", "department": "Executive Operations",
        "title": "Executive Morning Briefing",
        "purpose": "Give the GM and heads of department a single, decision-led view of the day's risks, priorities, and actions before service begins.",
        "business_outcome": "Faster, better-coordinated decisions; fewer surprises; a shared operational picture across departments.",
        "scope": "Daily leadership briefing covering all departments and the day's guest and operational profile.",
        "roles_responsible": ["General Manager", "Duty Manager", "Department Heads"],
        "required_systems": ["PMS", "Reporting / BI", "Executive Intelligence"],
        "preconditions": ["Overnight report compiled", "Arrivals, VIPs, events, and alerts aggregated"],
        "procedure": [
            "Aggregate the day's signals: occupancy, arrivals/VIPs, revenue trend, staffing, maintenance backlog, compliance, weather, guest complaints.",
            "Lead with what needs a decision today, then group alerts by department.",
            "Assign an owner and a by-when to each priority action.",
            "Distribute the briefing and confirm the actions awaiting approval are cleared before service.",
        ],
        "decision_tree": [
            {"condition": "a risk (weather, staffing shortfall, VIP-sensitive event) is flagged", "action": "assign a named owner and a mitigation before the briefing closes"},
            {"condition": "items are awaiting human approval from overnight agents", "action": "the Duty Manager clears or escalates them at the briefing"},
        ],
        "escalation_rules": ["Unresolved high risks escalate to the GM for a same-morning decision."],
        "quality_standards": ["Briefing leads with decisions, not status.", "Every priority has an owner and a deadline."],
        "kpis": ["Actions closed same-day", "Briefing on-time rate", "Repeat/unowned issues"],
        "common_mistakes": ["A status recital with no decisions or owners.", "Alerts surfaced without who-owns-what."],
        "ai_summary": "Aggregate the day's operational signals, lead with decisions, assign owner+deadline to each priority, clear items awaiting approval before service.",
        "related_sops": ["FO-101", "MN-401", "FIN-610"],
        "search_keywords": ["executive", "morning briefing", "gm", "priorities", "risks", "daily", "leadership", "operations"],
        "quiz": [{"question": "What should the morning briefing lead with?", "answer": "What needs a decision today — not a status recital."}],
        "follow_up_actions": ["Assign owners to priorities", "Clear items awaiting approval"],
        "category_tags": ["executive", "coordination"], "priority": "critical",
    },
    # ===================== GUEST EXPERIENCE =====================
    {
        "sop_id": "GX-201", "department": "Guest Experience",
        "title": "Guest Complaint Recovery",
        "purpose": "Recover service failures quickly and empathetically so a complaint becomes loyalty, and the root cause is captured and fixed.",
        "business_outcome": "Higher recovery-to-loyalty conversion; better review scores; fewer repeat failures.",
        "scope": "All guest complaints across channels, in-stay and post-stay.",
        "roles_responsible": ["Guest Relations", "Duty Manager", "Department Head"],
        "required_systems": ["Guest Profile / CRM", "Messaging", "Case log"],
        "preconditions": ["Recovery authority levels published", "Case log available"],
        "procedure": [
            "Acknowledge within 15 minutes; listen fully and own the issue without deflecting.",
            "Log the complaint with specifics and the guest's desired outcome.",
            "Offer a recovery gesture within the duty manager's authority; act, don't just promise.",
            "Fix the immediate issue, then capture the root cause for the responsible department.",
            "Follow up before departure to confirm the guest is satisfied.",
        ],
        "decision_tree": [
            {"condition": "the recovery required exceeds the frontline authority level", "action": "escalate to the Duty Manager for approval before committing compensation"},
            {"condition": "the complaint reveals a systemic issue (repeat across guests)", "action": "raise it to the Department Head as a root-cause action, not just a one-off gesture"},
        ],
        "escalation_rules": ["Compensation beyond the published authority level requires Duty Manager approval; systemic issues escalate to the Department Head."],
        "quality_standards": ["Acknowledged within 15 minutes.", "Every complaint followed up before departure.", "Root cause logged, not just the gesture."],
        "kpis": ["Time-to-acknowledge", "Recovery-to-loyalty conversion", "Repeat-complaint rate"],
        "common_mistakes": ["Promising a gesture and not delivering it.", "Fixing the symptom without capturing the root cause."],
        "ai_summary": "Acknowledge within 15 min, own it, log it, deliver a gesture within authority (escalate if beyond), fix the root cause, follow up before departure.",
        "related_sops": ["FO-101", "FB-214"],
        "search_keywords": ["complaint", "recovery", "guest", "service failure", "compensation", "apology", "review"],
        "quiz": [{"question": "What is the acknowledgement window for a guest complaint?", "answer": "Within 15 minutes."}],
        "follow_up_actions": ["Log root cause to the responsible department", "Follow up before departure"],
        "category_tags": ["guest", "recovery", "loyalty"], "priority": "critical",
    },
    # ===================== SECURITY =====================
    {
        "sop_id": "SEC-901", "department": "Security",
        "title": "Fire Alarm & Emergency Evacuation",
        "purpose": "Protect life first in any fire or emergency alarm through a calm, rehearsed, role-clear response.",
        "business_outcome": "Guest and staff safety; regulatory compliance; controlled, confident emergency handling.",
        "scope": "All fire alarms and evacuation events across the property.",
        "roles_responsible": ["Security Manager", "Duty Manager", "Fire Wardens", "Engineering"],
        "required_systems": ["Fire panel", "PA / mass-notification", "Guest manifest"],
        "preconditions": ["Wardens assigned per shift", "Assembly points published", "Panel monitored"],
        "procedure": [
            "On alarm, verify the zone at the fire panel and dispatch security to confirm.",
            "If confirmed or unverifiable, initiate evacuation via PA and warden sweep; call emergency services.",
            "Wardens sweep assigned zones, assist mobility-impaired guests, and direct to assembly points.",
            "Account for guests and staff at assembly using the manifest; report status to the incident commander.",
            "Do not re-admit until the fire service and Duty Manager authorise all-clear; log the incident.",
        ],
        "decision_tree": [
            {"condition": "the alarm cannot be verified as false within the drill standard", "action": "treat it as real and evacuate — never assume a false alarm"},
            {"condition": "a guest is unaccounted for at assembly", "action": "report immediately to the incident commander and fire service with the last-known location"},
        ],
        "escalation_rules": ["Every alarm is commanded by the Duty Manager/Security Manager; re-entry requires fire-service authorisation."],
        "quality_standards": ["Life safety before property.", "Assembly accountability completed every event.", "Incident logged for audit."],
        "kpis": ["Evacuation/accountability time", "Drill pass rate", "Compliance audit result"],
        "common_mistakes": ["Assuming a false alarm and delaying evacuation.", "Re-admitting before an authorised all-clear."],
        "ai_summary": "Verify at the panel, evacuate if confirmed or unverifiable, warden sweep to assembly, account for all via manifest, re-admit only on authorised all-clear.",
        "related_sops": ["HR-501", "MN-401"],
        "search_keywords": ["fire", "alarm", "evacuation", "emergency", "safety", "assembly", "warden", "life safety"],
        "quiz": [{"question": "What is the rule when an alarm can't be verified as false?", "answer": "Treat it as real and evacuate."}],
        "follow_up_actions": ["Log the incident", "Debrief and update the risk register"],
        "category_tags": ["security", "safety", "emergency"], "priority": "critical",
    },
    # ===================== ENGINEERING =====================
    {
        "sop_id": "ENG-410", "department": "Engineering",
        "title": "Planned Preventive Maintenance (PPM) Cycle",
        "purpose": "Keep critical plant and guest-facing assets reliable through scheduled preventive maintenance, reducing breakdowns and out-of-order rooms.",
        "business_outcome": "Fewer reactive failures and OOO rooms; longer asset life; lower energy and repair cost.",
        "scope": "All critical plant (HVAC, elevators, pools plant, generators) and in-room assets on a PPM schedule.",
        "roles_responsible": ["Chief Engineer", "Engineering Technician", "Maintenance Coordinator"],
        "required_systems": ["CMMS", "Asset register"],
        "preconditions": ["Asset register current", "PPM calendar approved"],
        "procedure": [
            "Generate the week's PPM tasks from the asset register and calendar.",
            "Schedule guest-area work in low-impact windows and coordinate any room downtime with Front Office.",
            "Complete each task to the checklist; record readings and parts used in the CMMS.",
            "Raise a corrective work order for any defect found during PPM.",
        ],
        "decision_tree": [
            {"condition": "PPM requires taking a guest room or facility offline", "action": "coordinate the window with Front Office and block inventory in advance"},
            {"condition": "a reading is out of tolerance", "action": "raise a corrective work order and escalate if it is safety- or comfort-critical"},
        ],
        "escalation_rules": ["Out-of-tolerance readings on critical plant escalate to the Chief Engineer."],
        "quality_standards": ["PPM completion on schedule.", "Readings and parts recorded for every task."],
        "kpis": ["PPM completion rate", "Reactive-vs-planned ratio", "Asset downtime"],
        "common_mistakes": ["Deferring PPM under service pressure until it becomes a reactive failure."],
        "ai_summary": "Generate PPM from the asset register, schedule guest-area work in low-impact windows, complete to checklist with readings logged, raise corrective orders for defects.",
        "related_sops": ["MN-401", "POOL-1101"],
        "search_keywords": ["preventive maintenance", "ppm", "engineering", "plant", "hvac", "asset", "schedule"],
        "quiz": [{"question": "What must be recorded for every PPM task?", "answer": "Readings taken and parts used, in the CMMS."}],
        "follow_up_actions": ["Raise corrective orders for defects", "Update the asset register"],
        "category_tags": ["engineering", "reliability"], "priority": "high",
    },
    # ===================== FINANCE =====================
    {
        "sop_id": "FIN-610", "department": "Finance",
        "title": "Inventory Variance & Stock Control",
        "purpose": "Detect and stop inventory leakage across F&B and stores by reconciling issued stock to sales and investigating variance.",
        "business_outcome": "Reduced shrinkage and cost leakage; accurate margins; accountability across outlets.",
        "scope": "All controllable inventory: beverage, food, minibar, retail, and stores transfers.",
        "roles_responsible": ["Financial Controller", "Cost Controller", "Outlet Managers"],
        "required_systems": ["Inventory / stock control", "POS / Micros", "Procurement"],
        "preconditions": ["Par levels set", "Transfers recorded in system"],
        "procedure": [
            "Reconcile issued stock against POS sales per outlet on the count cycle.",
            "Record all internal transfers in the system at the time of movement, not retrospectively.",
            "Investigate any variance beyond the threshold before signing off the period.",
            "Report variance trends to the outlet managers and the morning briefing where material.",
        ],
        "decision_tree": [
            {"condition": "variance exceeds the control threshold (e.g. >5% on high-value stock)", "action": "hold sign-off and investigate unlogged transfers, comps, or over-pouring before closing the period"},
        ],
        "escalation_rules": ["Material or repeated variance escalates to the Financial Controller and the relevant Department Head."],
        "quality_standards": ["Transfers recorded at time of movement.", "No period signed off with unexplained variance."],
        "kpis": ["Inventory variance %", "Shrinkage value", "Transfer-logging compliance"],
        "common_mistakes": ["Recording transfers retrospectively, which hides leakage.", "Signing off a period with unexplained variance."],
        "ai_summary": "Reconcile issued stock to POS sales per outlet, log transfers at time of movement, investigate variance over threshold before sign-off; material variance escalates.",
        "related_sops": ["FB-210", "RET-1301"],
        "search_keywords": ["inventory", "variance", "stock control", "stock transfer", "internal transfer", "transfers", "stock movement", "leakage", "shrinkage", "transfer", "reconcile", "cost"],
        "quiz": [{"question": "When must internal stock transfers be recorded?", "answer": "At the time of movement, not retrospectively."}],
        "follow_up_actions": ["Investigate variance over threshold", "Report material trends to the briefing"],
        "category_tags": ["finance", "cost-control"], "priority": "high",
    },
    # ===================== RESERVATIONS =====================
    {
        "sop_id": "RES-701", "department": "Reservations",
        "title": "Group & Large-Party Arrival Coordination",
        "purpose": "Coordinate group and large-party arrivals across departments so rooming, luggage, F&B, and billing run without friction.",
        "business_outcome": "Smooth high-volume arrivals; protected experience and reviews; captured group ancillary revenue.",
        "scope": "All group blocks and large parties (weddings, corporate, tour series) from booking to arrival day.",
        "roles_responsible": ["Reservations Manager", "Front Office Manager", "Events", "Housekeeping"],
        "required_systems": ["PMS", "Reservation / group module", "Messaging"],
        "preconditions": ["Rooming list received", "Billing instructions confirmed"],
        "procedure": [
            "Confirm the rooming list, special requests, and billing routing at least 48h before arrival.",
            "Pre-block rooms and align Housekeeping on the readiness sequence for the block.",
            "Brief Front Office, Bell Desk, and F&B on the arrival window and any VIPs within the group.",
            "Stage a group check-in desk or lounge so the main desk stays clear for other guests.",
        ],
        "decision_tree": [
            {"condition": "the rooming list changes inside 24h", "action": "the Reservations Manager re-coordinates blocks with Housekeeping and Front Office and confirms billing impact"},
            {"condition": "the group contains VIPs", "action": "apply FO-101 VIP handling within the group flow"},
        ],
        "escalation_rules": ["Late rooming-list changes or billing disputes escalate to the Reservations Manager and Front Office Manager."],
        "quality_standards": ["Group arrivals handled off the main desk.", "Billing routing confirmed before arrival day."],
        "kpis": ["Group check-in throughput", "Group-related complaints", "Group ancillary capture"],
        "common_mistakes": ["Processing a large group at the main desk, blocking all other guests.", "Unconfirmed billing routing causing arrival-day disputes."],
        "ai_summary": "Confirm rooming list + billing 48h out, pre-block and sequence with Housekeeping, brief all arrival departments, stage a separate group check-in; VIPs get FO-101.",
        "related_sops": ["FO-101", "EVT-810", "HK-301"],
        "search_keywords": ["group", "arrival", "large party", "rooming list", "coordination", "wedding", "corporate", "block"],
        "quiz": [{"question": "Where should a large group be checked in?", "answer": "At a staged group desk/lounge, off the main desk."}],
        "follow_up_actions": ["Confirm billing routing", "Sequence readiness with Housekeeping"],
        "category_tags": ["reservations", "groups"], "priority": "high",
    },
    # ===================== EVENTS =====================
    {
        "sop_id": "EVT-810", "department": "Events",
        "title": "VIP Celebration & Occasion Handling",
        "purpose": "Turn birthdays, anniversaries, and VIP occasions into signature moments through cross-department coordination and precise timing.",
        "business_outcome": "Memorable guest moments that drive loyalty, reviews, and referral; captured event ancillary revenue.",
        "scope": "All flagged occasions and VIP celebrations, in-room and in-outlet.",
        "roles_responsible": ["Events / Guest Experience", "F&B", "Housekeeping", "Front Office"],
        "required_systems": ["Guest Profile / CRM", "Reservation", "Messaging"],
        "preconditions": ["Occasion captured on the profile at booking", "Owner assigned"],
        "procedure": [
            "Capture occasion details and preferences at booking and assign a single owner.",
            "Plan the touchpoints: amenity, timing, and any surprise, with each department's cue.",
            "Confirm timing across F&B, Housekeeping, and Front Office the day before.",
            "Execute discreetly and precisely; capture a photo/note for the profile and follow up.",
        ],
        "decision_tree": [
            {"condition": "the occasion is discovered at arrival (not pre-booked)", "action": "the owner assembles a rapid in-room touch within service constraints and logs it for future stays"},
        ],
        "escalation_rules": ["Timing conflicts across departments escalate to the occasion owner, who holds the master timeline."],
        "quality_standards": ["Every flagged occasion has a single owner and a confirmed timeline.", "Executed discreetly, on cue."],
        "kpis": ["Occasion execution rate", "Occasion-driven review mentions", "Event ancillary revenue"],
        "common_mistakes": ["No single owner, so touches are missed or mistimed.", "Occasion not written back to the profile for next time."],
        "ai_summary": "Capture the occasion at booking, assign one owner, plan cross-department touchpoints with cues, confirm timing day-before, execute discreetly and log for next stay.",
        "related_sops": ["FO-101", "GX-201", "RES-701"],
        "search_keywords": ["vip", "birthday", "anniversary", "celebration", "occasion", "event", "surprise", "amenity"],
        "quiz": [{"question": "What does every flagged occasion need?", "answer": "A single owner and a confirmed cross-department timeline."}],
        "follow_up_actions": ["Log the moment to the guest profile", "Follow up post-occasion"],
        "category_tags": ["events", "vip", "loyalty"], "priority": "high",
    },
    # ===================== SPA =====================
    {
        "sop_id": "SPA-1001", "department": "Spa",
        "title": "Spa Booking, Contraindication & Consultation",
        "purpose": "Book spa treatments safely and personally, screening for contraindications and tailoring to the guest while protecting therapist scheduling.",
        "business_outcome": "Safe, personalised spa experiences; higher treatment yield and rebooking; reduced no-shows.",
        "scope": "All spa and wellness bookings and pre-treatment consultations.",
        "roles_responsible": ["Spa Manager", "Spa Receptionist", "Therapist"],
        "required_systems": ["Spa scheduling", "Guest Profile / CRM"],
        "preconditions": ["Therapist rota and room availability current", "Consultation form available"],
        "procedure": [
            "Match the treatment, therapist, and room to the guest's request and schedule.",
            "Complete the health consultation and screen for contraindications before confirming.",
            "Confirm timing, arrival lead-time, and cancellation policy with the guest.",
            "Prepare the room and therapist notes; capture preferences for rebooking.",
        ],
        "decision_tree": [
            {"condition": "the consultation flags a contraindication (pregnancy, condition, injury)", "action": "the therapist adapts or declines the treatment and offers a safe alternative"},
            {"condition": "a same-day slot is unavailable", "action": "offer the nearest slot or an alternative treatment and add to a waitlist"},
        ],
        "escalation_rules": ["Any medical uncertainty escalates to the Spa Manager before proceeding."],
        "quality_standards": ["No treatment without a completed consultation.", "Preferences captured for rebooking."],
        "kpis": ["Treatment yield / utilisation", "Rebooking rate", "No-show rate"],
        "common_mistakes": ["Confirming a treatment before screening contraindications."],
        "ai_summary": "Match treatment/therapist/room, complete the health consultation and screen contraindications before confirming, set policy, capture preferences; medical uncertainty escalates.",
        "related_sops": ["POOL-1101", "GX-201"],
        "search_keywords": ["spa", "booking", "treatment", "contraindication", "consultation", "wellness", "therapist", "massage"],
        "quiz": [{"question": "What must happen before a spa treatment is confirmed?", "answer": "A completed health consultation screening for contraindications."}],
        "follow_up_actions": ["Capture preferences for rebooking", "Waitlist unmet requests"],
        "category_tags": ["spa", "wellness", "safety"], "priority": "standard",
    },
    # ===================== POOLS & BEACH =====================
    {
        "sop_id": "POOL-1101", "department": "Pools & Beach",
        "title": "Pool & Beach Opening Checklist",
        "purpose": "Open pool and beach areas safely and to standard each day, covering water safety, cleanliness, and premium inventory readiness.",
        "business_outcome": "Guest safety and comfort; protected premium inventory revenue (cabanas/day beds); compliance.",
        "scope": "Daily opening of all pools, beach areas, and premium loungers/cabanas.",
        "roles_responsible": ["Pool & Beach Supervisor", "Lifeguard", "Attendant", "Engineering"],
        "required_systems": ["Water-plant readings log", "Reservation (cabanas)", "Work-order"],
        "preconditions": ["Water plant checked", "Lifeguard on duty", "Weather checked"],
        "procedure": [
            "Test and log water chemistry (chlorine, pH); do not open outside safe range.",
            "Confirm lifeguard cover and check safety equipment before guests enter.",
            "Set out and inspect loungers, cabanas, and shades; flag any damage as a work order.",
            "Prepare cabana/day-bed reservations so premium inventory is captured, never given away free.",
        ],
        "decision_tree": [
            {"condition": "water chemistry is out of the safe range", "action": "keep the pool closed, notify Engineering, and re-test before opening"},
            {"condition": "a weather warning is active (storm/lightning)", "action": "delay or suspend opening and post signage until conditions clear"},
        ],
        "escalation_rules": ["Water-safety failures or weather hazards escalate to the Supervisor and Duty Manager; the area stays closed until cleared."],
        "quality_standards": ["No opening outside safe water range or without lifeguard cover.", "All premium inventory reserved and recorded."],
        "kpis": ["On-time safe opening rate", "Cabana/day-bed revenue capture", "Water-safety compliance"],
        "common_mistakes": ["Opening before water chemistry is confirmed safe.", "Giving away cabanas without capturing the booking/payment."],
        "ai_summary": "Test and log water chemistry, confirm lifeguard cover and equipment, inspect and reserve premium loungers/cabanas; unsafe water or weather keeps the area closed.",
        "related_sops": ["ENG-410", "SEC-901"],
        "search_keywords": ["pool", "beach", "opening", "checklist", "water safety", "cabana", "lifeguard", "weather"],
        "quiz": [{"question": "Can the pool open if water chemistry is out of safe range?", "answer": "No — it stays closed, Engineering is notified, and it is re-tested first."}],
        "follow_up_actions": ["Raise work orders for damaged inventory", "Capture cabana reservations"],
        "category_tags": ["pools", "beach", "safety", "revenue"], "priority": "high",
    },
    # ===================== RETAIL =====================
    {
        "sop_id": "RET-1301", "department": "Retail",
        "title": "Boutique Stock Count & Charge-to-Room",
        "purpose": "Keep boutique inventory accurate and charge purchases correctly, whether paid directly or posted to the guest folio.",
        "business_outcome": "Accurate retail margins; captured charge-to-room revenue; reduced shrinkage.",
        "scope": "All boutique/retail sales and stock across outlets.",
        "roles_responsible": ["Retail Supervisor", "Cost Controller", "Front Office"],
        "required_systems": ["POS", "PMS (folio)", "Inventory"],
        "preconditions": ["Par levels set", "Charge-to-room authority confirmed"],
        "procedure": [
            "Ring every sale into POS; for charge-to-room, verify the guest and room before posting to the folio.",
            "Reconcile counted stock to POS sales on the count cycle.",
            "Investigate variance beyond threshold before sign-off.",
            "Replenish against par and record transfers at time of movement.",
        ],
        "decision_tree": [
            {"condition": "a charge-to-room cannot verify the guest/room", "action": "take direct payment instead of posting to a folio"},
        ],
        "escalation_rules": ["Variance beyond threshold or a charge dispute escalates to the Retail Supervisor and Cost Controller."],
        "quality_standards": ["Charge-to-room verified before posting.", "No sign-off with unexplained variance."],
        "kpis": ["Retail variance %", "Charge-to-room accuracy", "Sell-through vs par"],
        "common_mistakes": ["Posting a charge-to-room without verifying the guest, causing a folio dispute."],
        "ai_summary": "Ring all sales to POS, verify guest/room before charge-to-room, reconcile stock to sales, investigate variance before sign-off, replenish to par with logged transfers.",
        "related_sops": ["FIN-610"],
        "search_keywords": ["retail", "boutique", "stock count", "charge to room", "folio", "inventory", "variance"],
        "quiz": [{"question": "What must be verified before a charge-to-room is posted?", "answer": "The guest identity and room."}],
        "follow_up_actions": ["Investigate variance", "Replenish to par"],
        "category_tags": ["retail", "cost-control"], "priority": "standard",
    },
    # ===================== TRANSPORTATION =====================
    {
        "sop_id": "TR-1201", "department": "Transportation",
        "title": "Airport Transfer & Guest Pickup",
        "purpose": "Deliver punctual, branded airport transfers with accurate flight tracking so arrivals begin the experience the moment they land.",
        "business_outcome": "On-time, premium transfers; reduced missed pickups; strong first and last impression; captured transfer revenue.",
        "scope": "All arrival and departure transfers and internal guest transport.",
        "roles_responsible": ["Transport Coordinator", "Chauffeur", "Front Office", "Guest Relations"],
        "required_systems": ["Transfer scheduling", "Flight tracking", "PMS", "Messaging"],
        "preconditions": ["Flight details captured on the reservation", "Vehicle and chauffeur assigned"],
        "procedure": [
            "Confirm flight numbers and monitor live flight status for every scheduled transfer.",
            "Dispatch the chauffeur with a branded name board and the guest's preferences.",
            "Adjust the pickup for delays proactively and message the guest a clear meeting point.",
            "On arrival at the property, hand over warmly to Front Office for a seamless check-in.",
        ],
        "decision_tree": [
            {"condition": "the flight is delayed or diverted", "action": "the Transport Coordinator re-times the pickup automatically and notifies the guest, so no one waits"},
            {"condition": "the guest cannot be located at the meeting point", "action": "the chauffeur contacts Guest Relations to reach the guest before leaving"},
        ],
        "escalation_rules": ["Any missed or at-risk pickup escalates to the Transport Coordinator and Duty Manager."],
        "quality_standards": ["Live flight tracking on every transfer.", "Guest never left waiting without contact.", "Warm handover to Front Office."],
        "kpis": ["On-time pickup rate", "Missed-pickup incidents", "Transfer revenue capture"],
        "common_mistakes": ["Not tracking the flight, so a delayed or early arrival is missed."],
        "ai_summary": "Track flights live, dispatch a branded chauffeur with preferences, re-time proactively for delays and message the guest, hand over warmly to Front Office.",
        "related_sops": ["FO-101", "RES-701"],
        "search_keywords": ["airport", "transfer", "pickup", "chauffeur", "flight tracking", "transport", "arrival", "departure"],
        "quiz": [{"question": "What must be monitored for every scheduled transfer?", "answer": "Live flight status."}],
        "follow_up_actions": ["Message the guest a meeting point", "Warm handover to Front Office"],
        "category_tags": ["transport", "arrival"], "priority": "high",
    },
]

from .corpus_ext import EXT_RAW  # noqa: E402
from .corpus_ext2 import EXT2_RAW  # noqa: E402

# Validated SOP objects for the demo knowledge base (core + depth passes).
DEMO_SOPS: list[SOP] = [SOP.from_dict(d) for d in _RAW + EXT_RAW + EXT2_RAW]


def load_demo_kb() -> list[SOP]:
    """Return the authored demo knowledge base as validated SOP objects."""
    return list(DEMO_SOPS)
