"""Velocity Demo Knowledge Base — extended corpus, depth pass 2.

Adds coverage in the thinner departments to take the KB past 40 SOPs. Same schema,
same retrieval and guardrails; original, luxury-standard, no proprietary content.
"""
from __future__ import annotations

EXT2_RAW: list[dict] = [
    # ===================== RETAIL =====================
    {
        "sop_id": "RET-1305", "department": "Retail", "title": "Retail Returns & Exchanges",
        "purpose": "Handle boutique returns and exchanges fairly and consistently while protecting margin and the guest relationship.",
        "business_outcome": "Guest goodwill preserved; controlled refund leakage; accurate stock and folio adjustments.",
        "scope": "All boutique/retail returns, exchanges, and refunds.",
        "roles_responsible": ["Retail Supervisor", "Front Office", "Finance"],
        "required_systems": ["POS", "PMS (folio)", "Inventory"],
        "preconditions": ["Returns policy published", "Refund authority levels set"],
        "procedure": [
            "Verify the original sale (receipt or folio charge) and the item condition against the returns policy.",
            "For an exchange, adjust POS and stock; for a refund, process to the original payment method or reverse the room charge.",
            "Restock saleable items; quarantine damaged goods for the cost controller.",
            "Record every return with reason and approver for audit.",
        ],
        "decision_tree": [
            {"condition": "the item is outside the returns window or used", "action": "the Retail Supervisor decides on goodwill within policy, and records the reason"},
            {"condition": "the original charge was to the room and the guest has checked out", "action": "coordinate the refund with Finance to the settled payment method"},
        ],
        "escalation_rules": ["Refunds beyond the frontline authority level require Retail Supervisor approval; disputes go to Finance."],
        "quality_standards": ["Original sale verified before any refund.", "Every return logged with reason and approver."],
        "kpis": ["Return/refund rate", "Refund value vs threshold", "Restock accuracy"],
        "common_mistakes": ["Refunding without verifying the original sale, opening the door to leakage."],
        "ai_summary": "Verify the original sale and condition, process the exchange/refund to the right method, restock or quarantine, and log every return with reason and approver.",
        "related_sops": ["RET-1301", "FIN-615"],
        "search_keywords": ["return", "exchange", "refund", "retail", "boutique", "receipt", "restock", "policy"],
        "quiz": [{"question": "What must be verified before any retail refund?", "answer": "The original sale (receipt or folio charge) and the item condition."}],
        "follow_up_actions": ["Restock or quarantine the item", "Log the return for audit"],
        "category_tags": ["retail", "cost-control", "guest"], "priority": "standard",
    },
    # ===================== HOUSEKEEPING =====================
    {
        "sop_id": "HK-320", "department": "Housekeeping", "title": "Laundry & Guest Garment Handling",
        "purpose": "Process guest and hotel laundry accurately and on time, protecting garments and capturing valet-laundry revenue.",
        "business_outcome": "On-time, damage-free laundry; captured valet revenue; fewer guest complaints.",
        "scope": "All guest valet laundry, dry cleaning, and hotel linen processing.",
        "roles_responsible": ["Laundry Supervisor", "Room Attendant", "Front Office"],
        "required_systems": ["Laundry tracking", "PMS (folio)"],
        "preconditions": ["Turnaround times and pricing published", "Garment tagging in place"],
        "procedure": [
            "Collect and tag each guest garment against the room and a laundry list; note any pre-existing damage.",
            "Process by care label and the requested service (same-day, express); check pockets.",
            "Quality-check, package, and deliver within the quoted turnaround; post charges to the folio.",
            "Log any damage or delay and initiate recovery.",
        ],
        "decision_tree": [
            {"condition": "a garment has no care label or is delicate/high-value", "action": "confirm the method with the guest before processing to avoid damage liability"},
            {"condition": "a garment is damaged in processing", "action": "escalate to the Laundry Supervisor for a documented recovery gesture"},
        ],
        "escalation_rules": ["Damage claims or missed express turnarounds escalate to the Laundry Supervisor and Duty Manager."],
        "quality_standards": ["Every garment tagged to the room; pre-existing damage noted.", "Delivered within the quoted turnaround."],
        "kpis": ["On-time laundry rate", "Damage/complaint rate", "Valet-laundry revenue"],
        "common_mistakes": ["Not noting pre-existing damage, causing disputes.", "Ignoring a care label and damaging a garment."],
        "ai_summary": "Tag garments to the room and note damage, process by care label and service level, QC and deliver on time, post to folio; delicates get confirmed first.",
        "related_sops": ["HK-301", "FO-115"],
        "search_keywords": ["laundry", "valet", "dry cleaning", "garment", "linen", "wash", "turnaround", "care label"],
        "quiz": [{"question": "What is noted when collecting a guest garment?", "answer": "Pre-existing damage, and the garment tagged to the room and laundry list."}],
        "follow_up_actions": ["Post charges to the folio", "Log any damage/delay"],
        "category_tags": ["housekeeping", "revenue"], "priority": "standard",
    },
    # ===================== EXECUTIVE OPERATIONS =====================
    {
        "sop_id": "EX-615", "department": "Executive Operations", "title": "Daily Revenue & Yield Review",
        "purpose": "Review occupancy, rate, and revenue daily so pricing and inventory decisions are proactive, not reactive.",
        "business_outcome": "Higher RevPAR through timely rate/inventory decisions; aligned commercial and operations teams.",
        "scope": "Daily commercial review across rooms, F&B, and ancillary revenue.",
        "roles_responsible": ["General Manager", "Revenue Manager", "Reservations", "F&B Manager"],
        "required_systems": ["PMS", "Revenue-management system", "Reporting / BI"],
        "preconditions": ["Pace and pickup reports available", "Competitor/market data on hand"],
        "procedure": [
            "Review occupancy on the books, pickup, and pace vs forecast for the coming days.",
            "Assess rate positioning against demand and the competitive set; decide rate/restriction moves.",
            "Check ancillary revenue (F&B, spa, cabanas) and flag idle premium inventory.",
            "Assign commercial actions with owners; feed material risks into the morning briefing.",
        ],
        "decision_tree": [
            {"condition": "pickup is pacing below forecast for a near date", "action": "the Revenue Manager adjusts rate/restrictions or opens promotions to stimulate demand"},
            {"condition": "premium inventory (cabanas, suites) is idle", "action": "trigger targeted upsell via Guest Experience and F&B"},
        ],
        "escalation_rules": ["Significant forecast misses escalate to the GM for a same-day commercial decision."],
        "quality_standards": ["Rate decisions are data-based, not habitual.", "Every commercial action has an owner."],
        "kpis": ["RevPAR", "Pickup vs forecast", "Ancillary revenue per available room"],
        "common_mistakes": ["Holding rates by habit while pace falls, losing RevPAR."],
        "ai_summary": "Review occupancy/pickup/pace daily, position rate against demand and comp set, activate idle premium inventory, and assign owned commercial actions.",
        "related_sops": ["EX-601", "RES-710", "POOL-1101"],
        "search_keywords": ["revenue", "yield", "occupancy", "rate", "revpar", "pickup", "forecast", "pricing", "commercial"],
        "quiz": [{"question": "What should a rate decision be based on?", "answer": "Demand and the competitive set (data), not habit."}],
        "follow_up_actions": ["Assign commercial actions", "Flag idle premium inventory for upsell"],
        "category_tags": ["executive", "revenue"], "priority": "high",
    },
    # ===================== GUEST EXPERIENCE =====================
    {
        "sop_id": "GX-215", "department": "Guest Experience", "title": "VIP Recognition & Preference Management",
        "purpose": "Recognise and act on guest preferences at every touchpoint so loyalty is earned through consistency, not chance.",
        "business_outcome": "Higher repeat-guest loyalty and spend; personalised service that scales across shifts.",
        "scope": "All returning and VIP guests, across departments and stays.",
        "roles_responsible": ["Guest Relations", "Front Office", "Housekeeping", "F&B"],
        "required_systems": ["Guest Profile / CRM", "PMS"],
        "preconditions": ["Preference fields maintained on the profile", "Pre-arrival profile review scheduled"],
        "procedure": [
            "Review the guest profile before arrival; brief the relevant departments on preferences and history.",
            "Deliver on known preferences (room, pillow, dining, activities) without the guest having to ask.",
            "Capture new preferences observed during the stay back to the profile the same shift.",
            "Acknowledge milestones (repeat visits, tier, occasions) with a fitting recognition touch.",
        ],
        "decision_tree": [
            {"condition": "a returning guest has a preference the current room can't meet", "action": "the owner arranges an alternative or an equivalent gesture before arrival"},
        ],
        "escalation_rules": ["Missed preferences for a top-tier guest escalate to Guest Relations for same-stay recovery."],
        "quality_standards": ["Preferences delivered proactively, not on request.", "New preferences captured the same shift."],
        "kpis": ["Repeat-guest satisfaction", "Preference-capture rate", "Loyalty conversion"],
        "common_mistakes": ["Preferences captured on paper that never reach the profile, so the next stay repeats the miss."],
        "ai_summary": "Review the profile pre-arrival and brief departments, deliver known preferences proactively, capture new ones the same shift, and recognise milestones.",
        "related_sops": ["FO-101", "GX-201", "EVT-810"],
        "search_keywords": ["vip", "preference", "recognition", "loyalty", "returning guest", "profile", "personalisation", "repeat"],
        "quiz": [{"question": "When should a newly observed guest preference be recorded?", "answer": "Back to the guest profile the same shift."}],
        "follow_up_actions": ["Write new preferences to the profile", "Brief departments pre-arrival"],
        "category_tags": ["guest", "loyalty"], "priority": "high",
    },
    # ===================== ENGINEERING =====================
    {
        "sop_id": "ENG-420", "department": "Engineering", "title": "Pool Plant & Water Systems Safety",
        "purpose": "Keep pool, spa, and domestic water systems safe and compliant, controlling waterborne risk (including Legionella).",
        "business_outcome": "Guest safety and regulatory compliance; avoided closures and incidents.",
        "scope": "All pool/spa plant and domestic hot/cold water systems.",
        "roles_responsible": ["Chief Engineer", "Engineering Technician", "Pool & Beach Supervisor"],
        "required_systems": ["Water-treatment log", "CMMS"],
        "preconditions": ["Water-safety plan in place", "Testing schedule approved"],
        "procedure": [
            "Test and log pool/spa water chemistry to standard on schedule; dose within safe ranges.",
            "Monitor domestic water temperatures and run the Legionella control regime (flushing, temperature checks).",
            "Keep results in the water-treatment log; act on any out-of-range reading immediately.",
            "Coordinate any closure with Pool & Beach and the Duty Manager.",
        ],
        "decision_tree": [
            {"condition": "a water reading is out of the safe range", "action": "isolate the affected system, remediate, and keep it closed until re-tested safe"},
            {"condition": "a Legionella risk indicator is triggered", "action": "escalate to the Chief Engineer and follow the water-safety plan before reopening"},
        ],
        "escalation_rules": ["Any water-safety exceedance escalates to the Chief Engineer; affected systems stay closed until cleared."],
        "quality_standards": ["No system runs outside safe water parameters.", "Every test logged."],
        "kpis": ["Water-safety compliance", "Out-of-range incidents", "Closure hours"],
        "common_mistakes": ["Skipping temperature/Legionella checks, creating a hidden safety risk."],
        "ai_summary": "Test and log pool/spa chemistry and domestic water temps on schedule, run the Legionella regime, isolate and remediate out-of-range systems until re-tested safe.",
        "related_sops": ["POOL-1101", "ENG-410", "SPA-1005"],
        "search_keywords": ["water", "pool plant", "legionella", "chemistry", "safety", "domestic water", "treatment", "compliance"],
        "quiz": [{"question": "What happens when a water reading is out of the safe range?", "answer": "Isolate and remediate the system; keep it closed until re-tested safe."}],
        "follow_up_actions": ["Log the test", "Coordinate any closure with Pool & Beach"],
        "category_tags": ["engineering", "safety", "compliance"], "priority": "critical",
    },
    # ===================== RESERVATIONS =====================
    {
        "sop_id": "RES-715", "department": "Reservations", "title": "Cancellation & No-Show Policy",
        "purpose": "Apply cancellation and no-show policy consistently and fairly, protecting revenue while retaining goodwill.",
        "business_outcome": "Protected revenue from late cancellations/no-shows; consistent, dispute-free handling.",
        "scope": "All reservation cancellations, modifications, and no-shows across channels.",
        "roles_responsible": ["Reservations", "Front Office", "Duty Manager"],
        "required_systems": ["PMS", "Reservation / channel manager", "Payment gateway"],
        "preconditions": ["Rate-plan policies configured", "Charge authority levels set"],
        "procedure": [
            "Check the reservation's rate-plan cancellation terms before actioning any change.",
            "For an in-policy cancellation, release the room and confirm; for late/no-show, apply the policy charge per terms.",
            "Record the reason and any goodwill decision; notify the guest clearly.",
            "Rebalance inventory and pace after the change.",
        ],
        "decision_tree": [
            {"condition": "a loyalty guest cancels just outside the policy window", "action": "the Duty Manager may waive within goodwill limits and log the reason"},
            {"condition": "a no-show charge is disputed", "action": "review the booking terms and evidence before deciding (see FIN-615)"},
        ],
        "escalation_rules": ["Policy waivers beyond frontline authority require Duty Manager approval."],
        "quality_standards": ["Policy applied per the booked rate plan.", "Every waiver logged with a reason."],
        "kpis": ["No-show revenue captured", "Cancellation-related disputes", "Waiver rate"],
        "common_mistakes": ["Applying a generic policy instead of the booked rate-plan terms."],
        "ai_summary": "Check the rate-plan terms, release or charge per policy for cancellations/no-shows, log reasons and goodwill decisions, and rebalance inventory.",
        "related_sops": ["RES-710", "FIN-615", "FO-120"],
        "search_keywords": ["cancellation", "no-show", "policy", "reservation", "refund", "charge", "modification"],
        "quiz": [{"question": "What determines the cancellation charge?", "answer": "The booked rate plan's cancellation terms."}],
        "follow_up_actions": ["Log any waiver reason", "Rebalance inventory"],
        "category_tags": ["reservations", "revenue"], "priority": "standard",
    },
    # ===================== FOOD & BEVERAGE =====================
    {
        "sop_id": "FB-230", "department": "Food & Beverage", "title": "Bar Opening, Closing & Cash-Up",
        "purpose": "Open and close the bar to standard with accurate cash and stock reconciliation, protecting revenue and integrity.",
        "business_outcome": "Accurate cash and stock; reduced shrinkage; consistent, ready-to-serve outlets.",
        "scope": "All bar outlets at opening and close of service.",
        "roles_responsible": ["Bar Manager", "Bartender", "Finance"],
        "required_systems": ["POS / Micros", "Inventory", "Cash management"],
        "preconditions": ["Opening float set", "Par stock defined"],
        "procedure": [
            "Open: count the float, check par stock and equipment, and set up to the outlet checklist.",
            "During service: ring every sale, log comps/spills, and control high-value stock.",
            "Close: reconcile cash and card takings to POS, count stock against par, and record variance.",
            "Secure cash and stock; report any variance beyond threshold.",
        ],
        "decision_tree": [
            {"condition": "cash or stock variance exceeds the control threshold at close", "action": "the Bar Manager investigates before sign-off (unlogged comps, over-pouring, miskeys)"},
        ],
        "escalation_rules": ["Variance beyond threshold escalates to the Bar Manager and Finance."],
        "quality_standards": ["Every sale ringed; float and takings reconciled to POS.", "No close signed off with unexplained variance."],
        "kpis": ["Cash variance", "Stock variance %", "Comp/spill log completeness"],
        "common_mistakes": ["Signing off a close with unexplained variance instead of investigating."],
        "ai_summary": "Count the float and set up to checklist at open; ring all sales and log comps; at close reconcile cash/card to POS and stock to par, investigate variance before sign-off.",
        "related_sops": ["FB-210", "FIN-610"],
        "search_keywords": ["bar", "opening", "closing", "cash-up", "float", "reconcile", "variance", "stock", "till"],
        "quiz": [{"question": "What must reconcile at bar close?", "answer": "Cash and card takings to POS, and stock counted against par."}],
        "follow_up_actions": ["Secure cash and stock", "Report variance beyond threshold"],
        "category_tags": ["f&b", "cost-control"], "priority": "high",
    },
    # ===================== TRANSPORTATION =====================
    {
        "sop_id": "TR-1210", "department": "Transportation", "title": "Excursion & Activity Booking",
        "purpose": "Book guest excursions and activities safely and profitably, coordinating providers, timing, and transport.",
        "business_outcome": "Memorable guest experiences and ancillary revenue; safe, well-coordinated activities.",
        "scope": "All guest excursions, tours, and activities booked through the property.",
        "roles_responsible": ["Guest Experience / Concierge", "Transport Coordinator", "Approved providers"],
        "required_systems": ["Activity / booking system", "Guest Profile / CRM", "Payment gateway"],
        "preconditions": ["Vetted provider list with safety/insurance on file", "Pricing and cut-off times set"],
        "procedure": [
            "Match the activity to the guest's interests, fitness, and schedule; confirm any safety requirements.",
            "Book with an approved, insured provider and confirm timing, transport, and meeting point.",
            "Capture payment or post to the folio and issue a clear confirmation.",
            "Coordinate the transfer (TR-1201) and follow up on the guest's experience.",
        ],
        "decision_tree": [
            {"condition": "the activity has a safety or health requirement (diving, hiking, watersports)", "action": "confirm the guest meets it and the provider's safety/insurance is on file before booking"},
            {"condition": "weather threatens the activity", "action": "proactively rebook or refund per the provider's policy and inform the guest"},
        ],
        "escalation_rules": ["Only approved, insured providers are used; exceptions require management approval."],
        "quality_standards": ["Bookings only with vetted, insured providers.", "Clear confirmation with timing and meeting point."],
        "kpis": ["Excursion revenue", "Booking-to-experience satisfaction", "Safety incidents (target zero)"],
        "common_mistakes": ["Booking an unvetted provider, creating a safety and liability risk."],
        "ai_summary": "Match the activity to the guest, book only vetted insured providers, confirm timing/transport/meeting point, take payment, coordinate the transfer and follow up; safety requirements verified first.",
        "related_sops": ["TR-1201", "GX-215"],
        "search_keywords": ["excursion", "activity", "tour", "booking", "concierge", "provider", "transport", "diving", "hiking"],
        "quiz": [{"question": "Which providers may excursions be booked with?", "answer": "Only approved, insured, vetted providers."}],
        "follow_up_actions": ["Coordinate the transfer", "Follow up on the experience"],
        "category_tags": ["transport", "guest", "revenue"], "priority": "standard",
    },
]
