"""Velocity Demo Knowledge Base — extended SOP corpus (depth pass).

Adds 2-3 SOPs per department covering high-frequency and high-stakes operational
scenarios (lost luggage, room service, medical emergency, power outage, billing
disputes, banquet execution, weather suspension, and more). Same schema, same
retrieval, same guardrails as the core corpus — original, luxury-standard, no
proprietary content.
"""
from __future__ import annotations

EXT_RAW: list[dict] = [
    # ===================== FRONT OFFICE =====================
    {
        "sop_id": "FO-115", "department": "Front Office", "title": "Lost & Found and Lost Luggage",
        "purpose": "Recover, log, and return guest property quickly and accountably, whether lost in-house or in transit.",
        "business_outcome": "Higher recovery rate and guest trust; fewer disputes; auditable custody of valuables.",
        "scope": "All found items and reported lost/delayed luggage across the property.",
        "roles_responsible": ["Front Office", "Housekeeping", "Security", "Duty Manager"],
        "required_systems": ["Lost & Found log", "PMS", "Messaging"],
        "preconditions": ["Secure storage for valuables", "Custody log available"],
        "procedure": [
            "Log every found item immediately: description, location, finder, date/time — store valuables in the safe.",
            "For a lost-item report, search the guest's room, route, and outlets and record the search.",
            "Match reports to found items; verify ownership before release and capture a signature.",
            "For delayed luggage in transit, coordinate with the carrier and set a proactive update cadence to the guest.",
        ],
        "decision_tree": [
            {"condition": "the item is a valuable (passport, jewellery, cash, electronics)", "action": "secure in the safe, log custody, and escalate handling to the Duty Manager"},
            {"condition": "luggage is delayed by a carrier", "action": "arrange comfort items for the guest and own carrier follow-up until it arrives"},
        ],
        "escalation_rules": ["Valuables and any dispute over ownership escalate to the Duty Manager and Security."],
        "quality_standards": ["Every found item logged before storage.", "Ownership verified before release."],
        "kpis": ["Recovery/return rate", "Time-to-return", "Custody-log completeness"],
        "common_mistakes": ["Storing a valuable without logging custody, breaking the chain of accountability."],
        "ai_summary": "Log found items immediately, secure valuables in the safe, verify ownership before release, and own carrier follow-up for delayed luggage.",
        "related_sops": ["HK-301", "SEC-901"],
        "search_keywords": ["lost", "found", "luggage", "baggage", "delayed", "property", "valuables", "return"],
        "quiz": [{"question": "What must happen before a found item is stored?", "answer": "It is logged: description, location, finder, and time."}],
        "follow_up_actions": ["Match to open lost reports", "Update the guest on delayed luggage"],
        "category_tags": ["front office", "guest property"], "priority": "standard",
    },
    {
        "sop_id": "FO-120", "department": "Front Office", "title": "Overbooking & Guest Relocation (Walk)",
        "purpose": "Handle an oversell with a fair, generous relocation that protects the guest relationship and the property's reputation.",
        "business_outcome": "Minimised reputational and review damage from a walk; retained loyalty via generous, well-executed recovery.",
        "scope": "Any night where confirmed arrivals exceed sellable inventory.",
        "roles_responsible": ["Front Office Manager", "Duty Manager", "Reservations", "GM on duty"],
        "required_systems": ["PMS", "Partner-hotel contacts", "Messaging"],
        "preconditions": ["Walk policy and partner properties pre-agreed", "Relocation budget authority set"],
        "procedure": [
            "Identify who to walk by lowest impact: shortest stay, non-loyalty, not on a special occasion — never a VIP or long-stay.",
            "Secure a comparable-or-better partner hotel and cover transfer plus first-night cost.",
            "Communicate proactively and apologetically; offer a return upgrade and goodwill for a future stay.",
            "Log the incident, the guest's response, and the recovery for reputation follow-up.",
        ],
        "decision_tree": [
            {"condition": "the only candidates to walk are VIP/loyalty/occasion guests", "action": "escalate to the GM on duty; walking them is a last resort with executive sign-off"},
        ],
        "escalation_rules": ["Every walk is approved by the Duty Manager; VIP/loyalty walks require the GM on duty."],
        "quality_standards": ["Walked guests placed in comparable-or-better accommodation at the property's cost.", "Proactive, apologetic communication before arrival where possible."],
        "kpis": ["Walk incidents", "Walk-related review score", "Return-booking rate after a walk"],
        "common_mistakes": ["Walking a VIP or occasion guest to save cost — the reputational hit dwarfs the saving."],
        "ai_summary": "Walk the lowest-impact guest (never a VIP/occasion), place them comparable-or-better at our cost, communicate proactively, and log for reputation follow-up.",
        "related_sops": ["RES-710", "FO-101", "GX-201"],
        "search_keywords": ["overbooking", "walk", "relocation", "oversell", "no room", "sold out"],
        "quiz": [{"question": "Who should never be the first choice to walk?", "answer": "A VIP, loyalty, long-stay, or special-occasion guest."}],
        "follow_up_actions": ["Log the incident and recovery", "Arrange return upgrade"],
        "category_tags": ["front office", "recovery", "revenue"], "priority": "high",
    },
    # ===================== FOOD & BEVERAGE =====================
    {
        "sop_id": "FB-220", "department": "Food & Beverage", "title": "In-Room / In-Villa Dining Service",
        "purpose": "Deliver accurate, on-time, beautifully presented in-room dining with correct billing and minimal disturbance.",
        "business_outcome": "Higher in-room dining revenue and satisfaction; fewer order errors and re-fires.",
        "scope": "All in-room and in-villa food and beverage orders.",
        "roles_responsible": ["In-Room Dining", "Kitchen", "Order Taker"],
        "required_systems": ["POS / Micros", "PMS (folio)", "Order tracking"],
        "preconditions": ["Menu and allergen data current", "Delivery time standards set"],
        "procedure": [
            "Capture the order with allergen and preference checks; repeat it back to confirm.",
            "Quote an honest delivery time and fire to the kitchen with any dietary flags.",
            "Deliver within the quoted window; set up neatly, confirm the order, and post to the folio.",
            "Offer tray/trolley collection timing and log any issue for recovery.",
        ],
        "decision_tree": [
            {"condition": "an allergen or dietary restriction is flagged", "action": "confirm the kitchen adaptation and do not serve until verified (see FB-225)"},
            {"condition": "delivery will exceed the quoted time", "action": "call the guest proactively with a revised time, do not let them wait unaware"},
        ],
        "escalation_rules": ["Any allergen uncertainty escalates to the chef before service."],
        "quality_standards": ["Order read back and confirmed.", "Delivered within the quoted window.", "Correctly posted to the folio."],
        "kpis": ["On-time delivery rate", "Order accuracy", "In-room dining revenue"],
        "common_mistakes": ["Not reading the order back, causing errors and re-fires.", "Serving before confirming an allergen adaptation."],
        "ai_summary": "Capture with allergen checks and read-back, quote honest timing, deliver within window, present neatly, post to folio; allergens verified with the chef first.",
        "related_sops": ["FB-225", "FB-210"],
        "search_keywords": ["room service", "in-room dining", "in-villa", "order", "delivery", "tray", "amenity"],
        "quiz": [{"question": "What confirms an in-room order is correct before firing?", "answer": "Reading the order back to the guest with allergen/preference checks."}],
        "follow_up_actions": ["Post to folio", "Schedule tray collection"],
        "category_tags": ["f&b", "in-room dining"], "priority": "standard",
    },
    {
        "sop_id": "FB-225", "department": "Food & Beverage", "title": "Allergen & Dietary Requirement Handling",
        "purpose": "Prevent allergic reactions by verifying, communicating, and controlling dietary requirements end to end.",
        "business_outcome": "Guest safety and trust; zero preventable allergen incidents; regulatory compliance.",
        "scope": "All food service where a guest declares an allergy, intolerance, or dietary requirement.",
        "roles_responsible": ["Chef", "Server", "Restaurant Manager"],
        "required_systems": ["POS (allergen flags)", "Allergen matrix"],
        "preconditions": ["Allergen matrix per dish maintained", "Kitchen adaptation protocol published"],
        "procedure": [
            "Record the specific allergy/requirement at order and flag it in the POS.",
            "Check the allergen matrix; the chef confirms whether the dish is safe or how it will be adapted.",
            "Prepare on a controlled line to avoid cross-contact; the chef signs off the plate.",
            "Server confirms the safe dish to the guest at the table, by name of the requirement.",
        ],
        "decision_tree": [
            {"condition": "a dish cannot be made safe for the declared allergen", "action": "the chef offers a safe alternative rather than risk cross-contact"},
            {"condition": "the allergy is severe (anaphylaxis risk)", "action": "the Restaurant Manager oversees the order and confirms emergency readiness (see SEC-905)"},
        ],
        "escalation_rules": ["Any doubt about safety escalates to the chef; severe allergies to the Restaurant Manager."],
        "quality_standards": ["No allergen dish served without chef sign-off.", "Requirement confirmed to the guest at the table."],
        "kpis": ["Allergen incidents (target zero)", "Allergen flag compliance"],
        "common_mistakes": ["Assuming a dish is safe without checking the matrix or the chef."],
        "ai_summary": "Record and flag the allergen, verify via the matrix and chef, prepare cross-contact-free with chef sign-off, and confirm the safe dish to the guest.",
        "related_sops": ["FB-220", "SEC-905"],
        "search_keywords": ["allergen", "allergy", "dietary", "intolerance", "gluten", "nut", "cross-contamination", "vegan"],
        "quiz": [{"question": "What is required before an allergen-adapted dish leaves the kitchen?", "answer": "The chef's sign-off that it is safe."}],
        "follow_up_actions": ["Confirm the safe dish to the guest", "Log any incident"],
        "category_tags": ["f&b", "safety", "compliance"], "priority": "critical",
    },
    # ===================== HOUSEKEEPING =====================
    {
        "sop_id": "HK-310", "department": "Housekeeping", "title": "Stayover & Deep-Clean Service",
        "purpose": "Maintain in-stay room standards and schedule periodic deep cleans without disturbing guests.",
        "business_outcome": "Consistent cleanliness scores; longer asset life; respected guest privacy.",
        "scope": "All occupied rooms on stayover service and the deep-clean rotation.",
        "roles_responsible": ["Floor Supervisor", "Room Attendant", "Executive Housekeeper"],
        "required_systems": ["Housekeeping board", "PMS (DND/service prefs)"],
        "preconditions": ["Service preferences and DND captured", "Deep-clean rotation scheduled"],
        "procedure": [
            "Respect DND and service-time preferences; service when the guest is out or on request.",
            "Clean to the stayover checklist; replenish and reset to standard.",
            "Rotate deep-clean tasks (mattress, upholstery, descale) on schedule and log completion.",
            "Report any defect or lost item found during service.",
        ],
        "decision_tree": [
            {"condition": "DND persists past the service window", "action": "leave a service card and coordinate a later time via Front Office"},
        ],
        "escalation_rules": ["A room refusing service for multiple days is flagged to the Duty Manager for a welfare check."],
        "quality_standards": ["DND always respected.", "Deep-clean rotation completed on schedule and logged."],
        "kpis": ["Cleanliness score", "Deep-clean completion rate", "Service-refusal follow-up"],
        "common_mistakes": ["Entering against DND.", "Skipping the deep-clean rotation under time pressure."],
        "ai_summary": "Respect DND and preferences, service to the stayover checklist, keep the deep-clean rotation on schedule and logged, and report defects/lost items.",
        "related_sops": ["HK-301", "FO-115"],
        "search_keywords": ["stayover", "deep clean", "housekeeping", "dnd", "service", "replenish", "occupied room"],
        "quiz": [{"question": "What is always respected during stayover service?", "answer": "The guest's Do-Not-Disturb and service-time preferences."}],
        "follow_up_actions": ["Coordinate a later service time", "Raise defects/lost items"],
        "category_tags": ["housekeeping", "in-stay"], "priority": "standard",
    },
    # ===================== HUMAN RESOURCES =====================
    {
        "sop_id": "HR-510", "department": "Human Resources", "title": "Probation & Performance Review",
        "purpose": "Run fair, documented probation and performance reviews so retention and development decisions are evidence-based.",
        "business_outcome": "Better retention of strong hires; defensible decisions; clear development paths.",
        "scope": "All employees during probation and on the review cycle.",
        "roles_responsible": ["HR Manager", "Department Head"],
        "required_systems": ["HRIS", "Review templates"],
        "preconditions": ["Objectives set at hire", "Review calendar published"],
        "procedure": [
            "Set clear objectives and standards at hire; check in mid-probation with documented feedback.",
            "Complete the end-of-probation review with the Department Head; confirm, extend, or exit with reasons.",
            "Run scheduled performance reviews against objectives; agree a development plan.",
            "Record outcomes and next actions in the HRIS.",
        ],
        "decision_tree": [
            {"condition": "performance is below standard at end of probation", "action": "either a documented extension with a plan or a fair exit — never an undocumented pass"},
        ],
        "escalation_rules": ["Any exit or dispute is reviewed by the HR Manager for fairness and compliance."],
        "quality_standards": ["Every review documented with objectives and outcomes.", "No undocumented probation pass."],
        "kpis": ["Probation completion rate", "Post-probation retention", "Review on-time rate"],
        "common_mistakes": ["Passing probation by default without a documented review."],
        "ai_summary": "Set objectives at hire, check in mid-probation, complete a documented end-of-probation and cyclical reviews with a development plan, record in HRIS.",
        "related_sops": ["HR-501", "HR-515"],
        "search_keywords": ["probation", "performance", "review", "appraisal", "objectives", "development", "retention"],
        "quiz": [{"question": "What is never acceptable at end of probation?", "answer": "An undocumented pass with no review."}],
        "follow_up_actions": ["Agree a development plan", "Record outcomes in HRIS"],
        "category_tags": ["hr", "performance"], "priority": "standard",
    },
    {
        "sop_id": "HR-515", "department": "Human Resources", "title": "Offboarding & Exit Process",
        "purpose": "Offboard leavers cleanly and respectfully, protecting security, assets, and knowledge.",
        "business_outcome": "No security or access gaps; recovered assets; captured exit insight; positive alumni relationships.",
        "scope": "All departing employees, voluntary or involuntary.",
        "roles_responsible": ["HR Manager", "Department Head", "IT/Security", "Finance"],
        "required_systems": ["HRIS", "Access management", "Payroll"],
        "preconditions": ["Notice logged", "Offboarding checklist available"],
        "procedure": [
            "Confirm the leave date and run the offboarding checklist across IT, security, finance, and the department.",
            "Revoke system and physical access on the last working day — not before, not after.",
            "Recover assets (uniform, devices, keys) and settle final pay and entitlements.",
            "Hold an exit conversation and capture handover of responsibilities and knowledge.",
        ],
        "decision_tree": [
            {"condition": "the exit is involuntary/sensitive", "action": "coordinate access revocation timing with Security and HR to happen at notification"},
        ],
        "escalation_rules": ["Sensitive exits are coordinated by the HR Manager with Security."],
        "quality_standards": ["Access revoked exactly on the last working day.", "Assets recovered and final pay settled."],
        "kpis": ["Access-revocation timeliness", "Asset-recovery rate", "Exit-interview completion"],
        "common_mistakes": ["Leaving system access live after departure — a security gap.", "No knowledge handover, losing institutional memory."],
        "ai_summary": "Run the cross-team offboarding checklist, revoke access on the last day, recover assets, settle pay, and capture an exit + knowledge handover.",
        "related_sops": ["HR-501", "SEC-901"],
        "search_keywords": ["offboarding", "exit", "leaver", "resignation", "termination", "access", "handover", "assets"],
        "quiz": [{"question": "When is system access revoked for a leaver?", "answer": "On the last working day (or at notification for sensitive exits)."}],
        "follow_up_actions": ["Recover assets", "Capture knowledge handover"],
        "category_tags": ["hr", "security", "compliance"], "priority": "high",
    },
    # ===================== MAINTENANCE =====================
    {
        "sop_id": "MN-410", "department": "Maintenance", "title": "In-Stay Guest-Room Defect Response",
        "purpose": "Resolve a defect in an occupied room fast and discreetly, with a fallback that protects the guest experience.",
        "business_outcome": "Fewer negative reviews from in-room faults; faster resolution; protected guest comfort.",
        "scope": "Any maintenance issue reported in an occupied guest room.",
        "roles_responsible": ["Maintenance Coordinator", "Technician", "Front Office", "Duty Manager"],
        "required_systems": ["Work-order / CMMS", "PMS"],
        "preconditions": ["On-call trades available", "Alternative rooms visible"],
        "procedure": [
            "Acknowledge the guest promptly and give an honest time for a technician.",
            "Attend discreetly with the right parts; if a quick fix isn't possible, offer a room move.",
            "Coordinate any move with Front Office and Housekeeping; carry the guest's setup across.",
            "Confirm the fix or move with the guest and log the resolution.",
        ],
        "decision_tree": [
            {"condition": "the fault affects safety or comfort and can't be fixed quickly (AC, hot water, power, lock)", "action": "move the guest to an equivalent-or-better room immediately"},
        ],
        "escalation_rules": ["Comfort/safety faults that can't be resolved quickly escalate to the Duty Manager for a move decision."],
        "quality_standards": ["Guest acknowledged promptly with an honest ETA.", "A move offered when a quick fix isn't possible."],
        "kpis": ["In-room fault resolution time", "Fault-driven room moves", "Related review mentions"],
        "common_mistakes": ["Leaving a guest without hot water or AC while chasing a slow repair instead of moving them."],
        "ai_summary": "Acknowledge with an honest ETA, attend discreetly, offer an equivalent-or-better room move if no quick fix, coordinate the move, confirm and log.",
        "related_sops": ["MN-401", "HK-301", "FO-120"],
        "search_keywords": ["room defect", "maintenance", "in-stay", "ac", "hot water", "repair", "room move", "occupied"],
        "quiz": [{"question": "What do you do if a comfort fault can't be fixed quickly?", "answer": "Move the guest to an equivalent-or-better room immediately."}],
        "follow_up_actions": ["Coordinate the move with Front Office", "Log the resolution"],
        "category_tags": ["maintenance", "guest experience"], "priority": "high",
    },
    # ===================== EXECUTIVE OPERATIONS =====================
    {
        "sop_id": "EX-610", "department": "Executive Operations", "title": "Crisis & Incident Communication",
        "purpose": "Coordinate calm, accurate, single-voice communication during a serious incident to protect guests, staff, and reputation.",
        "business_outcome": "Controlled incident handling; protected safety and reputation; regulatory and stakeholder confidence.",
        "scope": "Any serious incident (safety event, security threat, outage, weather, reputational event).",
        "roles_responsible": ["General Manager", "Duty Manager", "Security", "Communications"],
        "required_systems": ["Mass-notification", "Incident log", "Stakeholder contacts"],
        "preconditions": ["Incident command roles assigned", "Holding statements pre-drafted"],
        "procedure": [
            "Stand up incident command with a single accountable commander.",
            "Establish one source of truth; brief staff before guests and align messaging.",
            "Communicate to guests factually and calmly; avoid speculation; update at set intervals.",
            "Log the timeline and decisions; conduct a debrief and update the risk register.",
        ],
        "decision_tree": [
            {"condition": "the incident involves injury, threat, or media interest", "action": "the GM leads external communication; staff refer all press to the commander"},
        ],
        "escalation_rules": ["All serious incidents are commanded by the GM/Duty Manager; external comms are single-voice."],
        "quality_standards": ["One source of truth.", "Staff briefed before guests.", "Timeline logged for audit."],
        "kpis": ["Time to controlled messaging", "Incident debrief completion", "Reputation impact"],
        "common_mistakes": ["Multiple uncoordinated voices creating confusion.", "Speculating before facts are confirmed."],
        "ai_summary": "Stand up single-commander incident command, one source of truth, brief staff before guests, communicate factually at intervals, log and debrief.",
        "related_sops": ["SEC-901", "SEC-905", "EX-601"],
        "search_keywords": ["crisis", "incident", "communication", "emergency", "command", "reputation", "media", "outage"],
        "quiz": [{"question": "Who owns external communication in a serious incident?", "answer": "A single voice — the GM/incident commander."}],
        "follow_up_actions": ["Log the incident timeline", "Debrief and update the risk register"],
        "category_tags": ["executive", "crisis"], "priority": "critical",
    },
    # ===================== GUEST EXPERIENCE =====================
    {
        "sop_id": "GX-210", "department": "Guest Experience", "title": "Online Review & Reputation Response",
        "purpose": "Respond to guest reviews promptly and authentically, resolving issues and reinforcing strengths across platforms.",
        "business_outcome": "Stronger online reputation and ranking; more direct bookings; closed-loop service improvement.",
        "scope": "All public reviews and post-stay feedback across platforms.",
        "roles_responsible": ["Guest Relations", "Duty Manager", "Department Heads"],
        "required_systems": ["Reputation platform", "Guest Profile / CRM"],
        "preconditions": ["Review monitoring in place", "Response tone guidelines set"],
        "procedure": [
            "Monitor reviews daily; respond within the target window in the property's voice.",
            "Thank specific praise by name of the team; address criticism with ownership and a concrete fix.",
            "Route the underlying issue to the responsible department as a root-cause action.",
            "Where a guest is identifiable, follow up privately to recover the relationship.",
        ],
        "decision_tree": [
            {"condition": "a review alleges a serious issue (safety, discrimination, hygiene)", "action": "escalate to the Duty Manager/GM and respond only after facts are confirmed"},
        ],
        "escalation_rules": ["Serious allegations escalate before any public response."],
        "quality_standards": ["Responses on-voice and within the target window.", "Criticism drives a routed root-cause action, not just a reply."],
        "kpis": ["Response rate and time", "Average rating trend", "Issues routed to root cause"],
        "common_mistakes": ["Copy-paste responses that ignore the specific feedback.", "Replying publicly to a serious allegation before verifying facts."],
        "ai_summary": "Monitor daily, respond on-voice within the window, own criticism with a concrete fix, route root causes to departments, follow up privately; verify serious allegations first.",
        "related_sops": ["GX-201", "EX-610"],
        "search_keywords": ["review", "reputation", "tripadvisor", "google", "feedback", "response", "rating", "online"],
        "quiz": [{"question": "What must a response to criticism include?", "answer": "Ownership plus a concrete fix, and the issue routed to root cause."}],
        "follow_up_actions": ["Route the root cause", "Private guest follow-up"],
        "category_tags": ["guest", "reputation"], "priority": "high",
    },
    # ===================== SECURITY =====================
    {
        "sop_id": "SEC-905", "department": "Security", "title": "Medical Emergency Response",
        "purpose": "Give an ill or injured guest or staff member the fastest, safest response through a clear, rehearsed protocol.",
        "business_outcome": "Life safety; confident, compliant emergency handling; reduced liability.",
        "scope": "All medical emergencies on property.",
        "roles_responsible": ["Security Manager", "Duty Manager", "First Aiders", "Front Office"],
        "required_systems": ["Emergency contacts", "Incident log", "AED locations"],
        "preconditions": ["Trained first aiders on each shift", "AEDs and first-aid kits stocked and located"],
        "procedure": [
            "On report, dispatch the nearest first aider and Security; call emergency medical services early.",
            "Provide first aid within training; retrieve the nearest AED for cardiac events.",
            "Clear access and direct paramedics to the exact location; assign someone to meet them.",
            "Protect privacy and manage bystanders; log the incident and follow up with the guest.",
        ],
        "decision_tree": [
            {"condition": "the person is unresponsive or not breathing normally", "action": "start CPR/AED immediately and ensure EMS is already called"},
            {"condition": "a known severe allergy is involved", "action": "coordinate with F&B/GX (FB-225) and locate any prescribed auto-injector"},
        ],
        "escalation_rules": ["Every medical emergency is logged and led by the Duty Manager/Security Manager."],
        "quality_standards": ["EMS called early, not late.", "Paramedics met and directed.", "Privacy protected; incident logged."],
        "kpis": ["Response time", "First-aider/AED readiness", "Incident documentation completeness"],
        "common_mistakes": ["Delaying the EMS call while assessing.", "No one assigned to meet and guide paramedics."],
        "ai_summary": "Dispatch first aider + Security, call EMS early, give first aid/AED, clear access and meet paramedics, protect privacy, log and follow up.",
        "related_sops": ["SEC-901", "FB-225", "EX-610"],
        "search_keywords": ["medical", "emergency", "first aid", "ambulance", "aed", "cpr", "injury", "collapse", "collapsed", "unconscious", "unresponsive", "fainted", "choking", "seizure", "sick", "ill"],
        "quiz": [{"question": "When is EMS called in a medical emergency?", "answer": "Early — as soon as the emergency is identified, not after assessment."}],
        "follow_up_actions": ["Log the incident", "Follow up with the guest"],
        "category_tags": ["security", "safety", "emergency"], "priority": "critical",
    },
    {
        "sop_id": "SEC-910", "department": "Security", "title": "Suspicious Activity & Unaccompanied Item",
        "purpose": "Respond to suspicious behaviour or unattended items proportionately, protecting guests without alarm.",
        "business_outcome": "Safety and deterrence; calm, professional handling; reduced risk.",
        "scope": "All reports of suspicious activity, unauthorized access, or unattended items.",
        "roles_responsible": ["Security", "Duty Manager"],
        "required_systems": ["CCTV", "Incident log", "Access control"],
        "preconditions": ["Patrol coverage", "Reporting channel published"],
        "procedure": [
            "Assess discreetly via CCTV and a nearby officer; avoid alarming guests.",
            "For an unattended item, cordon a small radius, attempt to identify the owner, and do not touch it.",
            "For suspicious behaviour, observe, engage politely if safe, and verify authorization.",
            "Escalate genuine threats to the Duty Manager and, if warranted, authorities; log the incident.",
        ],
        "decision_tree": [
            {"condition": "an item appears deliberately abandoned and owner can't be found", "action": "treat as a potential threat, cordon, and escalate to the Duty Manager/authorities"},
        ],
        "escalation_rules": ["Any credible threat escalates to the Duty Manager and, if warranted, law enforcement."],
        "quality_standards": ["Proportionate, discreet response.", "Every incident logged with CCTV reference."],
        "kpis": ["Response time", "False-alarm handling", "Incident documentation"],
        "common_mistakes": ["Over-reacting and alarming guests, or under-reacting to a genuine threat."],
        "ai_summary": "Assess discreetly, cordon unattended items without touching, verify authorization for suspicious behaviour, escalate genuine threats, and log everything.",
        "related_sops": ["SEC-901", "EX-610"],
        "search_keywords": ["suspicious", "security", "unattended", "bag", "package", "lobby", "briefcase", "item", "threat", "unauthorized", "cctv", "patrol"],
        "quiz": [{"question": "What do you do with an unattended item whose owner can't be found?", "answer": "Cordon it without touching and escalate as a potential threat."}],
        "follow_up_actions": ["Log with CCTV reference", "Debrief if escalated"],
        "category_tags": ["security", "safety"], "priority": "high",
    },
    # ===================== ENGINEERING =====================
    {
        "sop_id": "ENG-415", "department": "Engineering", "title": "Power Outage & Generator Failover",
        "purpose": "Maintain safety and essential services during a power loss through a rehearsed failover and recovery.",
        "business_outcome": "Guest safety and comfort during outages; protected critical systems; fast, orderly recovery.",
        "scope": "Any partial or full loss of mains power.",
        "roles_responsible": ["Chief Engineer", "Duty Manager", "Security", "Front Office"],
        "required_systems": ["Generator / UPS", "BMS", "Emergency lighting"],
        "preconditions": ["Generator tested under load on schedule", "Critical-load map maintained"],
        "procedure": [
            "Confirm generator/UPS pick-up of life-safety and critical loads (lighting, lifts, fire systems, servers).",
            "Verify guest-area emergency lighting and assist anyone in lifts.",
            "Brief Front Office to reassure guests with a clear status and expected restoration.",
            "On mains return, restore systems in a controlled sequence and log the event and any fault.",
        ],
        "decision_tree": [
            {"condition": "the generator fails to pick up critical loads", "action": "invoke manual procedures, prioritise life-safety, and escalate to the Chief Engineer immediately"},
            {"condition": "guests are trapped in a lift", "action": "Security and Engineering execute the lift-release protocol as first priority"},
        ],
        "escalation_rules": ["Failover failure or entrapment escalates immediately to the Chief Engineer and Duty Manager."],
        "quality_standards": ["Life-safety loads maintained.", "Guests in lifts assisted first.", "Controlled restoration on mains return."],
        "kpis": ["Failover success rate", "Time to reassure guests", "Restoration time"],
        "common_mistakes": ["Skipping scheduled load tests, so failover fails when it matters."],
        "ai_summary": "Confirm generator/UPS on critical loads, verify emergency lighting and free anyone in lifts, reassure guests via Front Office, restore in sequence and log.",
        "related_sops": ["ENG-410", "SEC-901", "EX-610"],
        "search_keywords": ["power outage", "blackout", "generator", "failover", "ups", "emergency lighting", "lift", "electrical"],
        "quiz": [{"question": "What is the first priority if guests are trapped in a lift during an outage?", "answer": "Execute the lift-release protocol — guest safety first."}],
        "follow_up_actions": ["Restore systems in sequence", "Log the event and any fault"],
        "category_tags": ["engineering", "safety", "emergency"], "priority": "critical",
    },
    # ===================== FINANCE =====================
    {
        "sop_id": "FIN-615", "department": "Finance", "title": "Billing Dispute & Folio Correction",
        "purpose": "Resolve billing disputes fairly and fast with proper authorization and an audit trail.",
        "business_outcome": "Guest trust preserved; leakage from unwarranted adjustments controlled; clean audit.",
        "scope": "All guest billing disputes and folio corrections.",
        "roles_responsible": ["Front Office", "Night Auditor", "Duty Manager", "Finance"],
        "required_systems": ["PMS (folio)", "POS", "Audit log"],
        "preconditions": ["Adjustment authority levels published", "Backup documentation accessible"],
        "procedure": [
            "Listen fully, pull the folio and backup (POS, signatures, agreements), and identify the specific line.",
            "If the charge is an error, correct it with the reason and appropriate authorization.",
            "If the charge is valid, explain it clearly with the supporting evidence.",
            "Record every adjustment with reason, approver, and reference for audit.",
        ],
        "decision_tree": [
            {"condition": "the adjustment exceeds the frontline authority level", "action": "escalate to the Duty Manager for approval before crediting"},
        ],
        "escalation_rules": ["Adjustments beyond the published authority level require Duty Manager approval; patterns go to Finance."],
        "quality_standards": ["Every adjustment carries a reason, approver, and reference.", "Valid charges explained with evidence."],
        "kpis": ["Dispute resolution time", "Adjustment value vs threshold", "Audit exceptions"],
        "common_mistakes": ["Crediting to make a dispute go away without checking evidence or authorization."],
        "ai_summary": "Pull the folio + backup, correct genuine errors with authorization or explain valid charges with evidence, and log every adjustment for audit.",
        "related_sops": ["FIN-610", "RET-1301", "GX-201"],
        "search_keywords": ["billing", "bill", "dispute", "disputed", "disputing", "chargeback", "charge dispute", "wrong charge", "billing error", "folio", "charge", "refund", "adjustment", "invoice", "correction", "overcharge"],
        "quiz": [{"question": "What must every folio adjustment record?", "answer": "The reason, the approver, and a reference — for audit."}],
        "follow_up_actions": ["Record the adjustment for audit", "Escalate beyond-threshold credits"],
        "category_tags": ["finance", "guest"], "priority": "high",
    },
    # ===================== RESERVATIONS =====================
    {
        "sop_id": "RES-710", "department": "Reservations", "title": "Overbooking Management & Yield",
        "purpose": "Manage the sell strategy and overbooking risk so the property maximises revenue without walking guests.",
        "business_outcome": "Higher RevPAR with controlled walk risk; balanced occupancy and rate.",
        "scope": "Daily sell strategy, overbooking limits, and pickup management.",
        "roles_responsible": ["Reservations Manager", "Revenue Manager", "Front Office Manager"],
        "required_systems": ["PMS", "Revenue-management system", "Channel manager"],
        "preconditions": ["Historical no-show/cancellation data", "Overbooking limits approved"],
        "procedure": [
            "Set overbooking limits by room type from historical no-show and cancellation rates.",
            "Monitor pickup and pace daily; adjust rates and restrictions to shape demand.",
            "As arrival nears, reconcile oversell against real availability and pre-plan any relocation.",
            "Hand a clean, briefed arrivals picture to Front Office the day before.",
        ],
        "decision_tree": [
            {"condition": "projected arrivals will exceed inventory on the night", "action": "trigger the relocation pre-plan (FO-120) and secure partner rooms in advance"},
        ],
        "escalation_rules": ["Overbooking beyond approved limits requires Revenue Manager sign-off."],
        "quality_standards": ["Overbooking within approved, data-based limits.", "Relocation pre-planned, never improvised at the desk."],
        "kpis": ["RevPAR", "Walk incidents", "No-show accuracy"],
        "common_mistakes": ["Overbooking on gut feel instead of no-show data, forcing avoidable walks."],
        "ai_summary": "Set data-based overbooking limits, manage pickup and rate daily, reconcile oversell near arrival and pre-plan relocation, brief Front Office ahead.",
        "related_sops": ["FO-120", "RES-701"],
        "search_keywords": ["overbooking", "yield", "revenue", "revpar", "pickup", "no-show", "sell strategy", "occupancy"],
        "quiz": [{"question": "What should overbooking limits be based on?", "answer": "Historical no-show and cancellation data by room type."}],
        "follow_up_actions": ["Pre-plan relocation if needed", "Brief Front Office"],
        "category_tags": ["reservations", "revenue"], "priority": "high",
    },
    # ===================== EVENTS =====================
    {
        "sop_id": "EVT-815", "department": "Events", "title": "Banquet Event Order (BEO) Execution",
        "purpose": "Execute events exactly to the signed BEO through tight cross-department coordination.",
        "business_outcome": "Flawless events that drive repeat bookings and referrals; captured event revenue; no execution gaps.",
        "scope": "All banquets, conferences, and private events with a signed BEO.",
        "roles_responsible": ["Events Manager", "Banquet Ops", "Kitchen", "AV/Engineering"],
        "required_systems": ["Events / BEO system", "POS", "Messaging"],
        "preconditions": ["Signed BEO distributed", "Pre-event meeting held"],
        "procedure": [
            "Distribute the signed BEO and hold a pre-event meeting so every department knows its cues.",
            "Set up to the BEO spec (layout, timing, menu, AV) and verify against the checklist before doors.",
            "Run the event to the timeline; the Events Manager owns live changes and communicates them.",
            "Capture actuals and any variance for billing, and debrief for the next event.",
        ],
        "decision_tree": [
            {"condition": "the client requests a change during the event", "action": "the Events Manager approves, communicates to all departments, and logs it for billing"},
        ],
        "escalation_rules": ["Scope or billing changes are owned by the Events Manager; conflicts escalate to F&B/GM."],
        "quality_standards": ["Setup verified against the BEO before doors open.", "Live changes communicated to all departments."],
        "kpis": ["Event execution accuracy", "Client satisfaction/rebooking", "Event revenue vs BEO"],
        "common_mistakes": ["Departments working from different BEO versions.", "Uncommunicated live changes causing service gaps."],
        "ai_summary": "Distribute the signed BEO, pre-event brief, set up and verify to spec, run to timeline with the Events Manager owning changes, capture actuals and debrief.",
        "related_sops": ["EVT-810", "RES-701", "FB-214"],
        "search_keywords": ["banquet", "beo", "event", "conference", "wedding", "setup", "catering", "execution"],
        "quiz": [{"question": "What must be verified before an event's doors open?", "answer": "Setup against the signed BEO checklist."}],
        "follow_up_actions": ["Capture actuals for billing", "Debrief for the next event"],
        "category_tags": ["events", "execution"], "priority": "high",
    },
    # ===================== SPA =====================
    {
        "sop_id": "SPA-1005", "department": "Spa", "title": "Spa Hygiene, Sanitation & Turnaround",
        "purpose": "Maintain clinical-grade hygiene and smooth room turnaround between spa treatments.",
        "business_outcome": "Guest safety and confidence; compliance; higher utilisation via fast, clean turnarounds.",
        "scope": "All treatment rooms, wet areas, and equipment between and after treatments.",
        "roles_responsible": ["Spa Manager", "Therapist", "Spa Attendant"],
        "required_systems": ["Spa scheduling", "Sanitation log"],
        "preconditions": ["Sanitation protocol published", "Linen and supplies stocked"],
        "procedure": [
            "Sanitise surfaces, equipment, and reusable tools between every guest to protocol.",
            "Change linens and reset the room to standard within the turnaround window.",
            "Maintain wet-area cleanliness and water-quality checks on schedule.",
            "Log sanitation completion and flag any supply or equipment issue.",
        ],
        "decision_tree": [
            {"condition": "a tool cannot be properly sanitised", "action": "remove it from service and use a compliant alternative"},
        ],
        "escalation_rules": ["Any hygiene or water-quality failure closes the area and escalates to the Spa Manager."],
        "quality_standards": ["Sanitation between every guest, logged.", "Turnaround within the window without cutting hygiene."],
        "kpis": ["Sanitation-log compliance", "Turnaround time", "Hygiene audit result"],
        "common_mistakes": ["Rushing turnaround by skipping sanitation steps."],
        "ai_summary": "Sanitise between every guest, change linens and reset within the window, keep wet areas and water quality to standard, and log completion.",
        "related_sops": ["SPA-1001", "POOL-1101"],
        "search_keywords": ["spa", "hygiene", "sanitation", "cleaning", "turnaround", "linen", "wet area", "disinfect"],
        "quiz": [{"question": "How often is equipment sanitised in the spa?", "answer": "Between every guest, to protocol, and logged."}],
        "follow_up_actions": ["Log sanitation", "Flag supply/equipment issues"],
        "category_tags": ["spa", "hygiene", "compliance"], "priority": "high",
    },
    # ===================== POOLS & BEACH =====================
    {
        "sop_id": "POOL-1105", "department": "Pools & Beach", "title": "Weather Suspension & Safe Reopening",
        "purpose": "Suspend and safely reopen pool and beach operations around weather hazards, protecting guests and premium revenue.",
        "business_outcome": "Guest safety in adverse weather; orderly reopening that recaptures revenue quickly.",
        "scope": "All pool and beach areas during storm, lightning, high-wind, or sea-state warnings.",
        "roles_responsible": ["Pool & Beach Supervisor", "Lifeguard", "Duty Manager"],
        "required_systems": ["Weather feed", "PA / signage", "Reservation (cabanas)"],
        "preconditions": ["Weather thresholds published", "Suspension/reopen checklist available"],
        "procedure": [
            "Monitor the weather feed; on a lightning/storm threshold, clear the water and beach and post signage.",
            "Secure loose furniture, umbrellas, and equipment; account for guests leaving the area.",
            "Keep guests informed of the reason and expected reopening via staff and signage.",
            "Reopen only after the all-clear and a safety re-check (water quality, equipment, lifeguard cover); re-seat cabana bookings.",
        ],
        "decision_tree": [
            {"condition": "lightning is within the safety threshold", "action": "clear the water immediately and suspend until the standard clear-time after the last strike"},
        ],
        "escalation_rules": ["Suspension and reopening decisions are owned by the Supervisor with the Duty Manager."],
        "quality_standards": ["Water cleared promptly on threshold.", "Reopening only after all-clear + safety re-check."],
        "kpis": ["Suspension response time", "Safe-reopen compliance", "Cabana revenue recovered"],
        "common_mistakes": ["Reopening too early after lightning, before the standard clear-time."],
        "ai_summary": "On a weather threshold, clear the water/beach and post signage, secure equipment, keep guests informed, reopen only after all-clear + safety re-check and re-seat cabanas.",
        "related_sops": ["POOL-1101", "SEC-901", "EX-610"],
        "search_keywords": ["weather", "storm", "lightning", "pool", "beach", "suspension", "reopen", "wind", "safety"],
        "quiz": [{"question": "When can the pool reopen after lightning?", "answer": "Only after the standard clear-time following the last strike and a safety re-check."}],
        "follow_up_actions": ["Re-seat cabana bookings", "Log the suspension"],
        "category_tags": ["pools", "beach", "safety", "revenue"], "priority": "high",
    },
    # ===================== TRANSPORTATION =====================
    {
        "sop_id": "TR-1205", "department": "Transportation", "title": "Valet Parking & Vehicle Handling",
        "purpose": "Provide secure, prompt valet parking with full accountability for guest vehicles and keys.",
        "business_outcome": "Premium arrival/departure experience; zero vehicle-handling disputes; captured parking revenue.",
        "scope": "All valet parking and guest vehicle handling.",
        "roles_responsible": ["Valet Supervisor", "Valet Attendant", "Security"],
        "required_systems": ["Valet ticketing", "Key management", "CCTV"],
        "preconditions": ["Ticketing and key custody system in place", "Parking capacity visible"],
        "procedure": [
            "Issue a valet ticket and note existing vehicle condition at drop-off.",
            "Secure keys in the key-management system with a clear custody record.",
            "Park in the assigned area; log the location against the ticket.",
            "On retrieval, verify the ticket, return the vehicle promptly, and confirm condition with the guest.",
        ],
        "decision_tree": [
            {"condition": "existing damage is noted at drop-off", "action": "record it with the guest's acknowledgement to prevent a later dispute"},
        ],
        "escalation_rules": ["Any damage claim or key-custody issue escalates to the Valet Supervisor and Security."],
        "quality_standards": ["Condition noted at drop-off.", "Keys in custody system, never loose.", "Prompt retrieval."],
        "kpis": ["Retrieval time", "Vehicle-handling incidents", "Parking revenue"],
        "common_mistakes": ["Not recording pre-existing damage, causing disputes at retrieval.", "Leaving keys unsecured."],
        "ai_summary": "Ticket and note vehicle condition at drop-off, secure keys with custody, log parking location, verify ticket and confirm condition on prompt retrieval.",
        "related_sops": ["TR-1201", "SEC-910"],
        "search_keywords": ["valet", "parking", "vehicle", "car", "keys", "retrieval", "damage"],
        "quiz": [{"question": "What is recorded at valet drop-off to prevent disputes?", "answer": "Existing vehicle condition/damage, with the guest's acknowledgement."}],
        "follow_up_actions": ["Log parking location", "Confirm condition on retrieval"],
        "category_tags": ["transport", "arrival"], "priority": "standard",
    },
]
