"""Firefly Estate Bequia — design-partner property knowledge pack (SEED).

A SECOND, INDEPENDENT knowledge corpus for the featured demonstration property:
Firefly Estate Hotel, Spring Valley, Bequia, Saint Vincent & the Grenadines.

Why this is a separate corpus and not merged into ``DEMO_SOPS``
---------------------------------------------------------------
Each property gets its own retrieval namespace. Merging a second property's
knowledge into the authored demo corpus would shift the TF-IDF weights and degrade
the published 95% retrieval@1 metric (this was measured and reverted on 2026-08-13).
Keeping properties isolated is also how the product actually works in production:
one tenant, one knowledge base, one set of citations.

PROVENANCE / GOVERNANCE — read before demonstrating
---------------------------------------------------
Every record below is seeded **from Firefly's own public website** and carries the
page it came from in ``source``. **Nothing here has been confirmed by the operator.**
Each record is therefore tagged ``confidence="unconfirmed"`` and
``approval_status="draft"``. The rule the product enforces, and that the console
displays, is:

    A fact does not become operator-confirmed until Firefly confirms it.
    Unconfirmed facts are shown to staff with a visible provenance badge.

``FIREFLY_GAPS`` records what the public web cannot answer (rates, check-in times,
transfers, villa service paths, ...). Those are deliberately ABSENT from the corpus
so the grounding guardrail refuses them — which is the honest behaviour and the
strongest thing to show a judge.

Replacing this seed with Firefly's real documents is a content change, not a code
change: same schema, same retriever, same guardrail.

Source: fireflybequia.com (public pages only) · Compiled 2026-08-15 · Seed v1
"""
from __future__ import annotations

from .schema import SOP

# Public source pages, referenced by key from each record's ``source`` field.
SOURCE_PAGES: dict[str, str] = {
    "home": "https://www.fireflybequia.com/",
    "accommodation": "https://www.fireflybequia.com/accommodation",
    "what-you-get": "https://www.fireflybequia.com/what-you-get",
    "eating-drinking": "https://www.fireflybequia.com/eating-drinking",
    "golf": "https://www.fireflybequia.com/golf",
    "plantation-tours": "https://www.fireflybequia.com/plantation-tours",
    "activities": "https://www.fireflybequia.com/activities",
    "water-sports": "https://www.fireflybequia.com/water-sports",
    "faqs": "https://www.fireflybequia.com/faqs",
    "booking-conditions": "https://www.fireflybequia.com/booking-conditions",
    "contact-us": "https://www.fireflybequia.com/contact-us",
    "truthful-asides": "https://www.fireflybequia.com/truthful-asides",
}

_UNCONFIRMED = {"confidence": "unconfirmed", "approval_status": "draft"}

_RAW: list[dict] = [
    # ============================ PROPERTY & GROUNDS ============================
    {
        "sop_id": "FF-101", "department": "Property & Grounds",
        "title": "Property Identity, Location & Access",
        "purpose": "Give any staff member or guest-facing agent one correct answer about where Firefly is, what it is, and how a guest reaches it.",
        "business_outcome": "Consistent first-touch answers; fewer misdirected arrivals; less time spent on the single enquiry channel.",
        "scope": "All enquiries about the property's location, character and how to get there.",
        "roles_responsible": ["Owner/Manager", "Reception", "Restaurant Host"],
        "procedure": [
            "Firefly Estate Hotel (also published as Firefly Bequia Plantation Hotel) is located at Spring Valley, Spring, Bequia, Saint Vincent & the Grenadines, VC0400.",
            "The property sits on over twenty acres of manicured grounds on a centuries-old historic estate.",
            "It is one mile from the main dock at Port Elizabeth and a short taxi ride from Bequia's airport.",
            "Describe it as a small boutique hotel offering every comfort of a larger hotel with the personal, attentive service of a small property.",
            "The restaurant is about five minutes by taxi from Port Elizabeth.",
        ],
        "decision_tree": [
            {"condition": "a guest asks for a transfer price or a specific pickup time", "action": "do not quote — no published transfer detail exists; route to the operator (gap G4)"},
        ],
        "escalation_rules": ["Any question about arrival logistics beyond location and distance goes to the owner/manager."],
        "quality_standards": ["Location and distance answered identically by every channel.", "No transfer price is ever invented."],
        "kpis": ["Location questions answered without escalation", "Misdirected arrivals"],
        "common_mistakes": ["Quoting a taxi fare or transfer time that has never been published."],
        "ai_summary": "Firefly Estate is a small boutique hotel on a 20+ acre historic estate at Spring Valley, Bequia — one mile from the main dock and a short taxi ride from the airport.",
        "related_sops": ["FF-102", "FF-604"],
        "search_keywords": ["location", "address", "where", "bequia", "spring valley", "dock", "port elizabeth", "airport", "estate", "boutique hotel", "grenadines"],
        "quiz": [{"question": "How far is Firefly from the main dock?", "answer": "One mile from the main dock at Port Elizabeth."}],
        "category_tags": ["property", "arrival"], "priority": "high",
        "source": "home, contact-us", **_UNCONFIRMED,
    },
    {
        "sop_id": "FF-102", "department": "Property & Grounds",
        "title": "The Estate — Grounds, Orchards & the 1789 Sugar Mill",
        "purpose": "Describe the estate's heritage assets accurately so staff and agents can answer heritage questions and sell the estate tour without embellishing.",
        "business_outcome": "Heritage is the property's differentiator; accurate description supports the tour revenue line.",
        "scope": "All questions about the estate's history, grounds, orchards and the sugar mill.",
        "roles_responsible": ["Owner/Manager", "Tour Guide"],
        "procedure": [
            "The estate covers over twenty acres of manicured grounds.",
            "The property is a centuries-old historic plantation estate with working orchards.",
            "A sugar mill dating to 1789 stands on the grounds and is a stop on the guided walk.",
            "Fruit sampling, coconut cracking and sugar cane pressing feature on the guided walk.",
            "Point guests who want to see the mill to the schedule and price in FF-503.",
        ],
        "escalation_rules": ["Requests for private heritage access outside tour hours go to the owner/manager."],
        "quality_standards": ["Only the published heritage facts are stated: 20+ acres, 1789 sugar mill, orchards."],
        "kpis": ["Estate tour bookings", "Heritage questions answered first time"],
        "common_mistakes": ["Inventing dates or history beyond the published 1789 sugar mill."],
        "ai_summary": "A centuries-old plantation estate of 20+ acres with orchards and a sugar mill dating to 1789, visited on the guided walk described in FF-503.",
        "related_sops": ["FF-503", "FF-504"],
        "search_keywords": ["sugar mill", "1789", "history", "heritage", "plantation", "orchard", "grounds", "acres", "estate"],
        "quiz": [{"question": "From what year does the sugar mill date?", "answer": "1789."}],
        "category_tags": ["property", "heritage", "activities"], "priority": "standard",
        "source": "home, plantation-tours", **_UNCONFIRMED,
    },
    # ============================== ACCOMMODATION ==============================
    {
        "sop_id": "FF-201", "department": "Accommodation",
        "title": "Hotel Rooms — Upper Floor (Coconut & Sea Cotton)",
        "purpose": "Describe the upper-floor hotel rooms precisely so a guest enquiry, a housekeeping brief or a new hire gets the same room facts.",
        "business_outcome": "Accurate room descriptions reduce arrival disappointment and mis-sold bookings.",
        "scope": "The two upper-floor hotel rooms: Coconut and Sea Cotton.",
        "roles_responsible": ["Owner/Manager", "Housekeeping", "Reception"],
        "preconditions": ["Guest has been told the rooms are reached up exterior stone stairs"],
        "procedure": [
            "Coconut and Sea Cotton are the two upper-floor hotel rooms, reached up exterior stone stairs, with Caribbean Sea views.",
            "Each has a mosquito-draped king four-poster bed, a high wooden ceiling and rattan ceiling fans.",
            "Each has a large air-conditioned walk-in closet containing the mini bar.",
            "Each has a large sea-pebble-tiled double shower opening to exterior views.",
            "Each has a spacious balcony with seating and sun loungers.",
            "The two rooms have a connecting door with privacy locks, so they can be sold as a pair to a family or group.",
        ],
        "decision_tree": [
            {"condition": "a guest has mobility difficulty with stairs", "action": "offer the lower-floor rooms (FF-202) or the Estate Cottage instead, and flag to the owner/manager — there is no published accessibility policy (gap G6)"},
        ],
        "escalation_rules": ["Accessibility questions escalate to the owner/manager; nothing is promised on the guest's behalf."],
        "quality_standards": ["Stairs are always mentioned before booking an upper-floor room.", "Connecting-door option offered to families."],
        "kpis": ["Room-description accuracy complaints (target zero)", "Family/pair bookings of connecting rooms"],
        "common_mistakes": ["Not mentioning the exterior stone stairs to a guest with mobility needs."],
        "ai_summary": "Coconut and Sea Cotton: upper-floor sea-view rooms up exterior stone stairs — king four-poster with mosquito netting, air-conditioned walk-in closet with mini bar, sea-pebble double shower, balcony, connecting door with privacy locks.",
        "related_sops": ["FF-202", "FF-205"],
        "search_keywords": ["coconut", "sea cotton", "upper floor", "room", "four-poster", "balcony", "shower", "stairs", "sea view", "connecting"],
        "quiz": [{"question": "Which two rooms are on the upper floor?", "answer": "Coconut and Sea Cotton."}],
        "category_tags": ["accommodation"], "priority": "high",
        "source": "accommodation", **_UNCONFIRMED,
    },
    {
        "sop_id": "FF-202", "department": "Accommodation",
        "title": "Hotel Rooms — Lower Floor (Cinnamon & Nutmeg)",
        "purpose": "Describe the lower-floor hotel rooms precisely and identify when they are the better recommendation.",
        "business_outcome": "Correct room matching on the first enquiry, without a site visit or a call back.",
        "scope": "The two lower-floor hotel rooms: Cinnamon and Nutmeg.",
        "roles_responsible": ["Owner/Manager", "Housekeeping", "Reception"],
        "procedure": [
            "Cinnamon and Nutmeg are the two lower-floor hotel rooms, in an elevated position on the estate.",
            "Each has a mosquito-draped king bed with crisp European linens.",
            "Each has an air-conditioned walk-in closet containing the mini bar.",
            "Each has a large sea-pebble-tiled double shower with exterior access.",
            "Each has a spacious balcony.",
            "The two rooms have a connecting door with privacy locks.",
        ],
        "decision_tree": [
            {"condition": "the guest asks which rooms avoid the exterior stone stairs", "action": "recommend the lower-floor rooms, and note the estate itself has steep steps in places (FF-901)"},
        ],
        "escalation_rules": ["Any accessibility guarantee must come from the owner/manager, not from an agent."],
        "quality_standards": ["Lower-floor rooms are offered whenever stairs are raised as a concern."],
        "kpis": ["Room-match accuracy", "Stair-related complaints"],
        "common_mistakes": ["Describing the lower rooms as step-free — the estate has steep steps elsewhere."],
        "ai_summary": "Cinnamon and Nutmeg: elevated lower-floor rooms — king bed with mosquito netting and European linens, air-conditioned walk-in closet with mini bar, sea-pebble double shower, balcony, connecting door with privacy locks.",
        "related_sops": ["FF-201", "FF-901"],
        "search_keywords": ["cinnamon", "nutmeg", "lower floor", "room", "king bed", "linens", "balcony", "shower", "connecting"],
        "quiz": [{"question": "Which two rooms are on the lower floor?", "answer": "Cinnamon and Nutmeg."}],
        "category_tags": ["accommodation"], "priority": "high",
        "source": "accommodation", **_UNCONFIRMED,
    },
    {
        "sop_id": "FF-203", "department": "Accommodation",
        "title": "The Estate Cottage",
        "purpose": "Describe the Estate Cottage so family and longer-stay enquiries are matched correctly on first contact.",
        "business_outcome": "Captures family bookings that the four hotel rooms cannot serve.",
        "scope": "All enquiries about the Estate Cottage.",
        "roles_responsible": ["Owner/Manager", "Housekeeping"],
        "procedure": [
            "The Estate Cottage sits within the estate near the main facilities.",
            "It has a master bedroom with a king four-poster bed and an en suite.",
            "It has a children's room configurable as a king or as two twin beds.",
            "Both bedrooms are fully air conditioned.",
            "There is a separate bathroom with a walk-in shower.",
            "It has an open, airy lounge, an open-plan kitchen, and a wrap-around balcony with estate views.",
        ],
        "decision_tree": [
            {"condition": "a family with children enquires about hotel rooms", "action": "offer the Estate Cottage as the family option before quoting connecting hotel rooms"},
        ],
        "escalation_rules": ["Occupancy limits and child policy beyond the published description go to the owner/manager (gap G6)."],
        "quality_standards": ["The children's-room configuration is always mentioned to families."],
        "kpis": ["Family enquiry conversion", "Cottage occupancy"],
        "common_mistakes": ["Quoting a maximum occupancy that has never been published."],
        "ai_summary": "The Estate Cottage: a self-contained cottage on the estate with a king four-poster master en suite, a children's room (king or twin), air conditioning, walk-in shower, lounge, open-plan kitchen and wrap-around balcony.",
        "related_sops": ["FF-204", "FF-205"],
        "search_keywords": ["cottage", "estate cottage", "family", "children", "twin", "kitchen", "self catering", "lounge", "balcony"],
        "quiz": [{"question": "How is the Estate Cottage children's room configured?", "answer": "As a king bed or as two twin beds."}],
        "category_tags": ["accommodation", "family"], "priority": "standard",
        "source": "accommodation", **_UNCONFIRMED,
    },
    {
        "sop_id": "FF-204", "department": "Villa Operations",
        "title": "Paradise Beach Villa — Description & Service Model",
        "purpose": "Describe the Paradise Beach Villa and make explicit that it is physically separate from the hotel but operationally dependent on it.",
        "business_outcome": "The villa is the highest-value unit and the clearest guest journey with no system behind it; getting its service path right protects the biggest revenue line.",
        "scope": "All enquiries and internal coordination for the Paradise Beach Villa.",
        "roles_responsible": ["Owner/Manager", "Housekeeping", "Restaurant"],
        "procedure": [
            "Paradise Beach Villa is a luxury, modern, self-catering four-bedroom villa on the beach with a private pool.",
            "The master bedroom has a king bed with an en suite shower; the second bedroom has a double with an en suite shower.",
            "Two further bedrooms (one double, one single) share a separate bathroom; there is a separate guest WC.",
            "The villa has an open-plan lounge and dining area, a large covered outdoor patio, a private pool, a BBQ and an outdoor shower.",
            "Daily maid service is included, and villa guests have access to the main hotel facilities.",
            "Housekeeping, provisioning, transport, restaurant bookings and activities for the villa all currently route back through the property's single enquiry channel (FF-701).",
        ],
        "decision_tree": [
            {"condition": "a villa guest makes a service request (housekeeping, provisioning, transport, a table, an activity)", "action": "log it against the villa and route it to the owner/manager — there is no documented villa service path yet (gap G7)"},
        ],
        "escalation_rules": ["Anything involving the villa's private pool, BBQ safety, or a same-day provisioning promise goes to the owner/manager."],
        "quality_standards": ["Daily maid service and hotel-facility access are always stated.", "No villa service turnaround time is promised until Firefly defines one."],
        "kpis": ["Villa request turnaround", "Villa requests resolved without the owner"],
        "common_mistakes": ["Promising a villa service turnaround time that has never been agreed."],
        "ai_summary": "Paradise Beach Villa: a four-bedroom self-catering beachfront villa with private pool, BBQ, outdoor shower, daily maid service and access to hotel facilities — operationally dependent on the hotel for every service request.",
        "related_sops": ["FF-203", "FF-701"],
        "search_keywords": ["villa", "paradise beach", "beach villa", "private pool", "self catering", "bbq", "maid service", "four bedroom"],
        "quiz": [{"question": "Is maid service included at Paradise Beach Villa?", "answer": "Yes — daily maid service is included, along with access to the main hotel facilities."}],
        "category_tags": ["accommodation", "villa"], "priority": "critical",
        "source": "accommodation", **_UNCONFIRMED,
    },
    {
        "sop_id": "FF-205", "department": "Accommodation",
        "title": "What Is Included With a Stay",
        "purpose": "Answer the highest-frequency pre-arrival question — 'what do we actually get?' — identically every time.",
        "business_outcome": "Removes a large share of repetitive enquiry traffic from the single contact channel.",
        "scope": "All in-room and stay-inclusion questions for the hotel rooms.",
        "roles_responsible": ["Owner/Manager", "Housekeeping", "Reception"],
        "procedure": [
            "Complimentary breakfast is included when the guest books directly via the website.",
            "Free wireless internet is included.",
            "Twice-daily maid service and turn-down service are included.",
            "Laundry is charged separately and is not included.",
            "Rooms include luxurious beds with mosquito netting (some four-poster), 250-thread-count European linens and down pillows, with hypoallergenic pillows available on request.",
            "Rooms have air conditioning and a ceiling fan, full-size custom bath amenities, tropical-weight bath robes, sarongs and a hairdryer.",
            "Rooms include a beach basket with towels, in-room tea and coffee, an in-room safe, and a selection of books and games.",
        ],
        "decision_tree": [
            {"condition": "the guest booked through a third-party channel rather than the website", "action": "do not promise complimentary breakfast — the inclusion is published for direct website bookings; confirm with the owner/manager"},
            {"condition": "the guest asks for hypoallergenic pillows", "action": "confirm the request to housekeeping before arrival — they are available on request"},
        ],
        "escalation_rules": ["Any inclusion promised outside this list must be confirmed by the owner/manager first."],
        "quality_standards": ["The direct-booking condition on breakfast is always stated.", "Laundry is always identified as a separate charge."],
        "kpis": ["Repetitive inclusion questions reaching the owner", "Billing disputes over laundry"],
        "common_mistakes": ["Promising complimentary breakfast on a third-party booking.", "Implying laundry is included because maid service is."],
        "ai_summary": "Included: breakfast on direct website bookings, free Wi-Fi, twice-daily maid and turn-down service, mosquito-netted beds with 250-thread-count European linens, down pillows (hypoallergenic on request), air conditioning and ceiling fan, bath amenities, robes, sarongs, hairdryer, beach basket, in-room tea and coffee, safe, books and games. Laundry is charged separately.",
        "related_sops": ["FF-201", "FF-202", "FF-402"],
        "search_keywords": ["included", "inclusions", "breakfast", "wifi", "internet", "maid service", "turndown", "laundry", "linens", "pillows", "robes", "safe", "amenities"],
        "quiz": [{"question": "Is laundry included in the room rate?", "answer": "No — laundry is charged separately."}],
        "category_tags": ["accommodation", "guest"], "priority": "critical",
        "source": "what-you-get, faqs", **_UNCONFIRMED,
    },
    # ============================ RATES & BOOKING ============================
    {
        "sop_id": "FF-301", "department": "Rates & Booking",
        "title": "Reservation Deposit & Balance Schedule",
        "purpose": "State the published deposit and balance terms exactly, so no member of staff and no agent softens or improvises them.",
        "business_outcome": "Protects cash flow at a four-room property where a single cancellation is material.",
        "scope": "Every room, cottage and villa reservation.",
        "roles_responsible": ["Owner/Manager"],
        "procedure": [
            "A 30% non-refundable deposit is required when making a reservation.",
            "The balance is charged sixty days before arrival.",
            "Bookings made with less than sixty days' notice are charged in full at the time of booking.",
            "These sums are also non-refundable in the event of a cancellation.",
            "Travel insurance is recommended to guests; the policy is strict because the property is small.",
        ],
        "decision_tree": [
            {"condition": "a guest asks for an exception to the deposit or balance terms", "action": "never grant it — route to the owner/manager, who is the only person who may vary published terms"},
            {"condition": "a guest asks what a stay costs", "action": "do not quote — no rates are published anywhere retrievable (gap G1); route to the owner/manager"},
        ],
        "escalation_rules": ["All rate quotes and all commercial exceptions escalate to the owner/manager without exception."],
        "quality_standards": ["The deposit is always described as non-refundable.", "No rate is ever quoted by an agent."],
        "kpis": ["Deposit terms disputed at arrival", "Rate enquiries answered without escalation (expected: zero)"],
        "common_mistakes": ["Describing the deposit as refundable, or implying flexibility that the published policy does not offer."],
        "ai_summary": "A 30% non-refundable deposit is taken at booking; the balance is charged 60 days before arrival; bookings inside 60 days are charged in full at booking; all sums are non-refundable on cancellation.",
        "related_sops": ["FF-302", "FF-303"],
        "search_keywords": ["deposit", "balance", "payment schedule", "non-refundable", "booking", "reservation", "60 days", "insurance"],
        "quiz": [{"question": "How much deposit is required at booking?", "answer": "30%, non-refundable."}],
        "category_tags": ["booking", "finance"], "priority": "critical",
        "source": "booking-conditions", **_UNCONFIRMED,
    },
    {
        "sop_id": "FF-302", "department": "Rates & Booking",
        "title": "Cancellation, Late Arrival & Early Departure Policy",
        "purpose": "Apply the published cancellation position consistently and without negotiation by staff.",
        "business_outcome": "Prevents revenue loss and disputes at a property where every room matters.",
        "scope": "All cancellations, shortened stays and late arrivals.",
        "roles_responsible": ["Owner/Manager"],
        "procedure": [
            "Deposit and balance sums are non-refundable in the event of a cancellation.",
            "Guests who arrive late or depart early remain responsible for the entire reservation: a late arrival or an early departure does not reduce what is owed.",
            "Recommend travel insurance at the point of booking, and explain that the policy is strict because the property is small.",
            "Any goodwill gesture is the owner/manager's decision alone and is never offered by staff or by an agent.",
        ],
        "decision_tree": [
            {"condition": "a guest cites illness, weather or a missed ferry", "action": "express sympathy, state the published policy, and route the case to the owner/manager without promising an outcome"},
        ],
        "escalation_rules": ["Every cancellation request involving money escalates to the owner/manager."],
        "quality_standards": ["The published policy is stated warmly but unchanged.", "No refund is ever implied by staff or an agent."],
        "kpis": ["Cancellation disputes", "Insurance uptake at booking"],
        "common_mistakes": ["Hinting at a possible refund to defuse a difficult conversation."],
        "ai_summary": "Cancellations forfeit the deposit and any balance paid; a guest who arrives late or departs early remains responsible for the whole reservation; travel insurance is recommended, and only the owner/manager may vary the policy.",
        "related_sops": ["FF-301"],
        "search_keywords": ["cancellation", "cancel", "refund", "non-refundable", "arrive late", "late arrival", "depart early", "early departure", "travel insurance", "policy", "what happens if"],
        "quiz": [{"question": "What happens if a guest departs early?", "answer": "They remain responsible for the entire reservation."}],
        "category_tags": ["booking", "finance"], "priority": "critical",
        "source": "booking-conditions", **_UNCONFIRMED,
    },
    {
        "sop_id": "FF-303", "department": "Rates & Booking",
        "title": "Accepted Currencies, Cards & Money on the Island",
        "purpose": "Answer payment and money questions accurately for guests arriving on a small island.",
        "business_outcome": "Removes a common pre-arrival anxiety and a repetitive enquiry.",
        "scope": "All payment-method and currency questions.",
        "roles_responsible": ["Owner/Manager"],
        "procedure": [
            "Prices are quoted in Eastern Caribbean dollars (EC$), at approximately 2.7 to the US dollar.",
            "The property accepts US dollars, EC dollars, British pounds, Visa and MasterCard.",
            "A bank operates on the island, so guests are not dependent on carrying all their money in.",
            "Tipping is not required but is gratefully accepted.",
        ],
        "decision_tree": [
            {"condition": "a guest asks whether American Express or a digital wallet is accepted", "action": "do not confirm — only Visa and MasterCard are published; route to the owner/manager"},
        ],
        "escalation_rules": ["Any payment method outside the published list is confirmed by the owner/manager before the guest is told yes."],
        "quality_standards": ["Only published payment methods are confirmed.", "The EC$/US$ rate is given as approximate, never as a guaranteed rate."],
        "kpis": ["Payment-method questions escalated", "Payment failures at checkout"],
        "common_mistakes": ["Confirming a card type that is not on the published list."],
        "ai_summary": "EC$ is the quoted currency (~2.7 to US$); US dollars, EC dollars, British pounds, Visa and MasterCard are accepted; there is a bank on the island; tipping is not required but is appreciated.",
        "related_sops": ["FF-301", "FF-605"],
        "search_keywords": ["currency", "payment", "credit card", "visa", "mastercard", "dollars", "pounds", "exchange rate", "bank", "money", "cash"],
        "quiz": [{"question": "Which cards are accepted?", "answer": "Visa and MasterCard."}],
        "category_tags": ["booking", "finance", "guest"], "priority": "high",
        "source": "booking-conditions, faqs", **_UNCONFIRMED,
    },
    # ============================ FOOD & BEVERAGE ============================
    {
        "sop_id": "FF-401", "department": "Food & Beverage",
        "title": "Restaurant & Bar — Access, Setting and Character",
        "purpose": "Describe the restaurant and bar accurately to hotel guests, villa guests, visiting boats and island residents.",
        "business_outcome": "The restaurant serves non-residents as well as guests; accurate description protects a revenue line that does not depend on occupancy.",
        "scope": "All restaurant and bar enquiries from any audience.",
        "roles_responsible": ["Owner/Manager", "Restaurant Host", "Bar"],
        "procedure": [
            "The restaurant and bar is open and welcoming to hotel guests and non-residents alike, and is a favourite with visiting boats, villa guests and local island residents.",
            "The kitchen serves tasty, fresh Modern Caribbean dishes using locally sourced and home-grown ingredients gathered daily from the plantation.",
            "The setting is open-air, with plantation and sea views.",
            "The restaurant is about five minutes by taxi from Port Elizabeth.",
            "Reservations are taken on the property's single Tel/WhatsApp line (see FF-701).",
        ],
        "decision_tree": [
            {"condition": "a caller asks for opening hours or the menu", "action": "do not state hours or dishes — neither is published (gap G2); take the enquiry and route it to the owner/manager"},
            {"condition": "a non-resident asks whether they may also use the pool or other facilities", "action": "do not confirm — there is no published day-pass or non-resident facility policy (gap G5)"},
        ],
        "escalation_rules": ["Opening hours, menu content and non-resident facility access all escalate to the owner/manager."],
        "quality_standards": ["Non-residents are made to feel welcome without being promised facility access.", "No menu item or service time is invented."],
        "kpis": ["Covers from non-residents", "Restaurant enquiries resolved without the owner"],
        "common_mistakes": ["Guessing dinner service times to be helpful — the most damaging possible error on this property."],
        "ai_summary": "An open-air restaurant and bar with plantation and sea views, serving fresh Modern Caribbean food from produce gathered daily on the plantation — open to hotel guests, villa guests, visiting boats and island residents alike.",
        "related_sops": ["FF-402", "FF-701"],
        "search_keywords": ["restaurant", "bar", "dinner", "lunch", "food", "caribbean", "non-resident", "boats", "reservation", "table", "dining", "open air"],
        "quiz": [{"question": "Is the restaurant open to people who are not staying at the hotel?", "answer": "Yes — it welcomes non-residents, visiting boats, villa guests and island residents."}],
        "category_tags": ["f&b", "revenue"], "priority": "critical",
        "source": "eating-drinking", **_UNCONFIRMED,
    },
    {
        "sop_id": "FF-402", "department": "Food & Beverage",
        "title": "Breakfast Inclusions & Special Diets",
        "purpose": "Handle dietary requirements and breakfast questions the way the property has publicly committed to.",
        "business_outcome": "Dietary confidence is a booking factor for a small property with one kitchen.",
        "scope": "Breakfast entitlement and all dietary requests.",
        "roles_responsible": ["Owner/Manager", "Kitchen"],
        "procedure": [
            "Complimentary breakfast is included when the guest books directly via the website.",
            "Fresh juices are included with breakfast; all other drinks are charged.",
            "The published position on diets is: we can cater to most special diets — please let us know what you require and we will do our best.",
            "Capture any dietary requirement at the time of booking and pass it to the kitchen before arrival, never on the day.",
        ],
        "decision_tree": [
            {"condition": "a guest declares a severe allergy", "action": "record it, tell the guest it has been passed to the kitchen, and route to the owner/manager for confirmation — never confirm an allergen-free guarantee on the kitchen's behalf"},
        ],
        "escalation_rules": ["Every severe allergy is confirmed by the owner/manager directly with the guest."],
        "quality_standards": ["Dietary requirements are captured at booking, not at the table.", "No allergen guarantee is given by an agent."],
        "kpis": ["Dietary requirements captured before arrival", "Dietary incidents (target zero)"],
        "common_mistakes": ["Guaranteeing an allergen-free preparation without the kitchen confirming it."],
        "ai_summary": "Breakfast is complimentary on direct website bookings and includes fresh juices (other drinks are charged); the property will cater to most special diets on request, and severe allergies are confirmed by the owner/manager.",
        "related_sops": ["FF-205", "FF-401"],
        "search_keywords": ["breakfast", "diet", "dietary", "allergy", "vegetarian", "vegan", "gluten", "juice", "drinks", "special requirements"],
        "quiz": [{"question": "Which drinks are included with breakfast?", "answer": "Fresh juices; all other drinks are charged."}],
        "category_tags": ["f&b", "guest"], "priority": "high",
        "source": "faqs, what-you-get", **_UNCONFIRMED,
    },
    # ============================ ACTIVITIES & GOLF ============================
    {
        "sop_id": "FF-501", "department": "Activities & Golf",
        "title": "Golf — Six-Hole Par-3 Cross-Country Course",
        "purpose": "Sell and explain the golf course accurately, including its unusual eco-friendly rules and its published prices.",
        "business_outcome": "A published, priced revenue line that any trained agent can book without the owner.",
        "scope": "All golf enquiries, tee times and membership questions.",
        "roles_responsible": ["Owner/Manager", "Reception"],
        "procedure": [
            "The course is a six-hole, par-3 cross-country golf course.",
            "It is eco-friendly: it uses flagpoles instead of greens and cups.",
            "A hole is completed when the ball hits the flagpole or comes to rest within one club length of it.",
            "Golf costs EC$50 per person; the green fee includes rental of clubs and balls, so guests need not bring their own.",
            "Annual membership is EC$260.",
            "Tee times are arranged on the property's WhatsApp line (see FF-701).",
        ],
        "decision_tree": [
            {"condition": "a guest asks whether they need to bring clubs", "action": "confirm that clubs and balls are included in the EC$50 fee"},
            {"condition": "a guest asks for a nine-hole round or a different price", "action": "state the published course and price only — six holes, EC$50; do not confirm any other configuration"},
        ],
        "escalation_rules": ["Group golf bookings and any price variation go to the owner/manager."],
        "quality_standards": ["The EC$50 fee is always stated as including club and ball rental.", "Only the published six-hole par-3 configuration is described."],
        "kpis": ["Golf rounds sold", "Annual memberships sold"],
        "common_mistakes": ["Describing the course as nine holes or quoting a price other than EC$50."],
        "ai_summary": "Golf costs EC$50 per person and the cost includes club and ball rental: a six-hole par-3 cross-country course using flagpoles instead of greens, annual membership EC$260, tee times booked by WhatsApp.",
        "related_sops": ["FF-502", "FF-701"],
        "search_keywords": ["golf", "golf cost", "golf price", "how much is golf", "tee time", "course", "par 3", "six hole", "clubs included", "clubs", "balls", "green fee", "membership", "flagpole", "per person"],
        "quiz": [{"question": "What does the EC$50 golf fee include?", "answer": "Rental of clubs and balls."}],
        "category_tags": ["activities", "revenue"], "priority": "high",
        "source": "golf", **_UNCONFIRMED,
    },
    {
        "sop_id": "FF-502", "department": "Activities & Golf",
        "title": "Croquet Lawn",
        "purpose": "Confirm the croquet offer and that it costs nothing.",
        "business_outcome": "A free amenity that increases on-property dwell time and bar spend.",
        "scope": "All croquet enquiries.",
        "roles_responsible": ["Reception", "Owner/Manager"],
        "procedure": [
            "The estate has a croquet lawn.",
            "Croquet is complimentary to all guests.",
            "Offer croquet proactively to guests with an unstructured afternoon, alongside the pool and the estate tour.",
        ],
        "escalation_rules": ["Equipment damage or a maintenance issue on the lawn is reported to the owner/manager."],
        "quality_standards": ["Croquet is always described as complimentary."],
        "kpis": ["On-property dwell time", "Bar spend on unstructured afternoons"],
        "common_mistakes": ["Charging for, or implying a charge for, croquet."],
        "ai_summary": "The croquet lawn is complimentary to all guests.",
        "related_sops": ["FF-501"],
        "search_keywords": ["croquet", "lawn", "complimentary", "free", "game", "activity"],
        "quiz": [{"question": "Is croquet chargeable?", "answer": "No — it is complimentary to all guests."}],
        "category_tags": ["activities"], "priority": "standard",
        "source": "golf", **_UNCONFIRMED,
    },
    {
        "sop_id": "FF-503", "department": "Activities & Golf",
        "title": "The Estate Tour — How Much It Costs, When It Runs, What It Covers",
        "purpose": "Quote, book and describe the estate tour precisely — its cost, its times, and the day it does not run.",
        "business_outcome": "The estate tour is the property's signature paid experience and its heritage differentiator.",
        "scope": "All estate tour enquiries and bookings.",
        "roles_responsible": ["Owner/Manager", "Tour Guide", "Reception"],
        "preconditions": ["Booking taken in advance — tours are not walk-up"],
        "procedure": [
            "The estate tour costs EC$15 per person and is a leisurely guided walk of approximately 45 minutes.",
            "It covers the orchards and the 1789 sugar mill, with fruit sampling, coconut cracking and sugar cane pressing.",
            "Children are welcome on the tour.",
            "Tours run daily except Mondays, at 11.00am and at 2.00pm.",
            "The scheduled estate tour price is EC$15 per person.",
            "Bookings are required in advance and are taken on the property's Tel/WhatsApp line.",
        ],
        "decision_tree": [
            {"condition": "a guest asks for a tour on a Monday", "action": "explain tours do not run on Mondays and offer the next available 11.00am or 2.00pm slot, or the private tour (FF-504)"},
            {"condition": "a group larger than eight wants a private tour", "action": "route to the owner/manager — the published private-tour maximum is eight persons"},
        ],
        "escalation_rules": ["Group sizes above eight, and any request outside the published times, go to the owner/manager."],
        "quality_standards": ["The Monday closure is always stated.", "Only the two published start times are offered."],
        "kpis": ["Tour bookings per week", "Tours declined for being fully booked"],
        "common_mistakes": ["Offering a Monday tour, or a start time other than 11.00am or 2.00pm."],
        "ai_summary": "The scheduled estate tour costs EC$15 per person: a 45-minute guided estate walk through the orchards and the 1789 sugar mill with fruit sampling, coconut cracking and cane pressing — daily except Mondays at 11.00am and 2.00pm, booking required.",
        "related_sops": ["FF-102", "FF-504"],
        "search_keywords": ["estate tour", "plantation tour", "tour price", "tour cost", "how much is the tour", "guided walk", "sugar mill", "orchard", "45 minutes", "monday", "11am", "2pm", "booking", "children", "per person"],
        "quiz": [{"question": "Which day does the estate tour not run?", "answer": "Mondays."}],
        "category_tags": ["activities", "heritage", "revenue"], "priority": "high",
        "source": "plantation-tours", **_UNCONFIRMED,
    },
    {
        "sop_id": "FF-504", "department": "Activities & Golf",
        "title": "Private Tour by Arrangement (maximum eight persons)",
        "purpose": "Handle private, by-arrangement tour requests within the published limits.",
        "business_outcome": "A higher-value variant of the signature experience for groups and special occasions.",
        "scope": "Private, by-arrangement tour enquiries only — the scheduled tour is FF-503.",
        "roles_responsible": ["Owner/Manager", "Tour Guide"],
        "procedure": [
            "A private tour can be arranged privately at any time, not only at the scheduled times in FF-503.",
            "The maximum group size for a private tour is eight persons.",
            "The private, by-arrangement price is EC$100 for the group.",
            "Confirm the time with the owner/manager before it is promised to the guest.",
        ],
        "decision_tree": [
            {"condition": "the party exceeds eight persons", "action": "do not confirm — route to the owner/manager, as eight is the published maximum"},
        ],
        "escalation_rules": ["Every private tour time is confirmed by the owner/manager before the guest is told it is booked."],
        "quality_standards": ["The eight-person maximum is always applied.", "No private tour time is confirmed by an agent alone."],
        "kpis": ["Private tours sold", "Private tour requests declined on group size"],
        "common_mistakes": ["Confirming a private tour time without the owner/manager."],
        "ai_summary": "A private, by-arrangement tour for a maximum of eight persons costs EC$100 for the group; the scheduled EC$15 per-person tour is FF-503.",
        "related_sops": ["FF-503"],
        "search_keywords": ["private tour", "privately arranged", "by arrangement", "group booking", "eight persons", "ec$100", "special occasion"],
        "quiz": [{"question": "What is the maximum group size for a private estate tour?", "answer": "Eight persons."}],
        "category_tags": ["activities", "revenue"], "priority": "standard",
        "source": "plantation-tours", **_UNCONFIRMED,
    },
    {
        "sop_id": "FF-505", "department": "Activities & Golf",
        "title": "Water Sports, Snorkelling & Diving — Third-Party Providers",
        "purpose": "Handle water-based activity requests where the provider is not Firefly.",
        "business_outcome": "Guests get the experience without Firefly assuming liability for a third party's operation.",
        "scope": "Snorkelling, diving, sailing and water sports enquiries.",
        "roles_responsible": ["Owner/Manager", "Reception"],
        "procedure": [
            "The property lists pool, hiking, yoga, sailing, water sports, weddings and honeymoons among available activities; no prices are published for these.",
            "Diving is run by Dive Bequia, a local PADI centre: they run the dive operation as a third party and Firefly does not run or operate it.",
            "Snorkelling around Bequia is excellent; gear can be rented locally or pre-booked.",
            "The property can supply ice chests, beverages, snacks, picnics, pizza, towels, beach chairs and Frisbees for a beach day.",
            "Refer diving enquiries to the local dive shop rather than quoting or booking on their behalf.",
        ],
        "decision_tree": [
            {"condition": "a guest asks for a price for diving, sailing, yoga or water sports", "action": "do not quote — no prices are published for these and diving is a third party; route to the owner/manager"},
        ],
        "escalation_rules": ["Any third-party booking made on a guest's behalf is authorised by the owner/manager."],
        "quality_standards": ["Third-party operations are always identified as third-party.", "No unpublished activity price is quoted."],
        "kpis": ["Activity referrals made", "Third-party incidents (target zero)"],
        "common_mistakes": ["Quoting a dive price, or implying Firefly runs the dive operation."],
        "ai_summary": "Diving is run by Dive Bequia, a third-party local PADI centre, not by Firefly; pool, hiking, yoga, sailing and water sports are available with no published prices; snorkel gear is rentable locally, and the property supplies beach kit, picnics and drinks.",
        "related_sops": ["FF-601"],
        "search_keywords": ["diving", "who runs the diving", "dive operator", "snorkel", "sailing", "water sports", "yoga", "hiking", "pool", "beach", "picnic", "dive bequia", "padi", "third party"],
        "quiz": [{"question": "Who operates the diving?", "answer": "Dive Bequia, a local third-party PADI centre — not Firefly."}],
        "category_tags": ["activities"], "priority": "standard",
        "source": "activities, water-sports, faqs", **_UNCONFIRMED,
    },
    # ============================== GUEST FAQ ==============================
    {
        "sop_id": "FF-601", "department": "Guest FAQ",
        "title": "The Estate Beach — Access, Character & Sand Flies",
        "purpose": "Set correct expectations about the property's own beach, including the one honest caveat.",
        "business_outcome": "A guest who is told about sand flies in advance is not a guest who complains about them afterwards.",
        "scope": "All beach questions from in-house guests.",
        "roles_responsible": ["Reception", "Owner/Manager"],
        "procedure": [
            "The property's own beach is about a five-minute walk through the estate.",
            "Describe it honestly as wild, but suitable for walking and swimming.",
            "Advise guests to avoid the beach in the late afternoon because of sand flies.",
            "Taxis to the main beaches take about ten minutes and cost little.",
            "Offer the beach basket, ice chest, chairs and picnic provisioning the property supplies.",
        ],
        "decision_tree": [
            {"condition": "a guest wants a manicured resort beach", "action": "be candid that the estate beach is wild, and point them to the main beaches ten minutes away by taxi"},
        ],
        "escalation_rules": ["Any safety concern on the beach walk is reported to the owner/manager."],
        "quality_standards": ["The sand-fly advice is given before the guest walks down, not after.", "The beach is never oversold as manicured."],
        "kpis": ["Beach-related complaints", "Beach provisioning requests fulfilled"],
        "common_mistakes": ["Describing the estate beach as a resort beach."],
        "ai_summary": "The estate's own beach is a five-minute walk through the grounds — wild but good for walking and swimming; avoid late afternoon because of sand flies, and the main beaches are about ten minutes by taxi.",
        "related_sops": ["FF-505", "FF-901"],
        "search_keywords": ["beach", "sand flies", "swimming", "walk", "taxi", "main beaches", "wild"],
        "quiz": [{"question": "When should guests avoid the estate beach?", "answer": "Late afternoon, because of sand flies."}],
        "category_tags": ["guest", "activities"], "priority": "high",
        "source": "faqs", **_UNCONFIRMED,
    },
    {
        "sop_id": "FF-602", "department": "Guest FAQ",
        "title": "Mosquitoes, Wildlife & Guest Safety Reassurance",
        "purpose": "Answer the anxiety questions a first-time Caribbean traveller asks before booking.",
        "business_outcome": "Removes a booking objection that would otherwise need the owner to answer personally.",
        "scope": "Pre-arrival questions about insects, animals and safety.",
        "roles_responsible": ["Reception", "Owner/Manager"],
        "procedure": [
            "Mosquitoes are generally not a problem on the property, and there is no malaria.",
            "There are no dangerous animals, fish or sharks.",
            "All beds have mosquito netting (see FF-201, FF-202).",
            "The estate has two dogs, Hope and Duke, several cats, and goats — mention this proactively to guests with allergies or a fear of dogs.",
        ],
        "decision_tree": [
            {"condition": "a guest declares an animal allergy or a fear of dogs", "action": "tell them about Hope, Duke, the cats and the goats before they book, and route to the owner/manager to agree how the stay is managed"},
            {"condition": "a guest asks for a medical or vaccination recommendation", "action": "do not advise — state only the published position that there is no malaria, and refer them to their own doctor"},
        ],
        "escalation_rules": ["Any medical question beyond the published position goes to the owner/manager and to the guest's own doctor."],
        "quality_standards": ["The resident animals are disclosed before booking, not on arrival.", "No medical advice is given."],
        "kpis": ["Animal-related surprises at arrival (target zero)"],
        "common_mistakes": ["Giving health or vaccination advice.", "Not disclosing the estate animals to an allergic guest."],
        "ai_summary": "Mosquitoes are generally not a problem and there is no malaria; there are no dangerous animals, fish or sharks; the estate is home to two dogs (Hope and Duke), several cats and goats, which is disclosed to guests before booking.",
        "related_sops": ["FF-901", "FF-201"],
        "search_keywords": ["mosquito", "malaria", "sharks", "dangerous animals", "dogs", "cats", "goats", "allergy", "safety", "insects"],
        "quiz": [{"question": "Which animals live on the estate?", "answer": "Two dogs (Hope and Duke), several cats and goats."}],
        "category_tags": ["guest", "safety"], "priority": "high",
        "source": "faqs, truthful-asides", **_UNCONFIRMED,
    },
    {
        "sop_id": "FF-603", "department": "Guest FAQ",
        "title": "Connectivity, Power & Sockets",
        "purpose": "Answer the practical questions a remote worker or a traveller with devices asks.",
        "business_outcome": "Wi-Fi and power questions are high-frequency and fully answerable — they should never reach the owner.",
        "scope": "Internet, mobile coverage and electrical questions.",
        "roles_responsible": ["Reception"],
        "procedure": [
            "There is free wifi in all rooms: Wi-Fi is available in every hotel room, in the Estate Cottage, in the Beach Villa, and in the bar and lounge.",
            "Cell coverage reaches most of the island.",
            "Power is 220–240 volts, 50 cycles, with UK three-pin sockets.",
            "Hairdryers are supplied in the rooms, so guests need not bring one.",
            "Advise guests from North America that they will need a UK-style adaptor.",
        ],
        "decision_tree": [
            {"condition": "a guest asks about the Wi-Fi speed or whether it supports video calls", "action": "do not quote a speed — none is published; confirm coverage only and route the specific question to the owner/manager"},
        ],
        "escalation_rules": ["A Wi-Fi outage is reported to the owner/manager immediately."],
        "quality_standards": ["Coverage locations are stated exactly.", "No bandwidth figure is invented."],
        "kpis": ["Connectivity questions escalated", "Wi-Fi outage response time"],
        "common_mistakes": ["Quoting an internet speed that has never been measured or published."],
        "ai_summary": "There is free wifi in all rooms: Wi-Fi covers every room, the Estate Cottage, the Beach Villa and the bar and lounge; cell coverage reaches most of the island; power is 220–240v, 50 cycles, UK three-pin, and hairdryers are supplied in the rooms.",
        "related_sops": ["FF-205"],
        "search_keywords": ["wifi", "wi-fi", "wifi in the rooms", "internet", "room internet", "cell", "mobile", "coverage", "power", "voltage", "sockets", "adaptor", "plug", "hairdryer", "rooms"],
        "quiz": [{"question": "What sockets does the property use?", "answer": "UK three-pin, 220–240v, 50 cycles."}],
        "category_tags": ["guest", "facilities"], "priority": "standard",
        "source": "faqs", **_UNCONFIRMED,
    },
    {
        "sop_id": "FF-604", "department": "Arrival & Transport",
        "title": "Reaching Bequia — Ferries and Island Access",
        "purpose": "Answer how a guest physically gets to Bequia, and be explicit about the routes that do not exist.",
        "business_outcome": "Prevents guests planning a journey on a ferry route that does not run — the single most damaging arrival error.",
        "scope": "All questions about getting to the island.",
        "roles_responsible": ["Owner/Manager", "Reception"],
        "procedure": [
            "There is no ferry from Barbados or from Saint Lucia to Bequia — state this plainly whenever those routes are raised.",
            "The ferry from Saint Vincent to Bequia takes about one hour.",
            "Bequia has an airport, a short taxi ride from the property.",
            "The property is one mile from the main dock at Port Elizabeth.",
        ],
        "decision_tree": [
            {"condition": "a guest asks for ferry times, an airline schedule, or a transfer price", "action": "do not quote — no schedule or transfer price is published by the property (gap G4); route to the owner/manager"},
            {"condition": "a guest plans to arrive via Barbados or Saint Lucia by sea", "action": "correct the plan immediately — no such ferry exists — and route them to the owner/manager to re-plan"},
        ],
        "escalation_rules": ["All arrival logistics beyond these published facts go to the owner/manager."],
        "quality_standards": ["The no-ferry-from-Barbados-or-St-Lucia fact is stated whenever those islands are mentioned.", "No ferry timetable is ever invented."],
        "kpis": ["Arrival plan corrections made before travel", "Missed arrivals"],
        "common_mistakes": ["Inventing a ferry time or a transfer fare to seem helpful."],
        "ai_summary": "There is no ferry from Barbados or Saint Lucia; the Saint Vincent–Bequia ferry takes about an hour; Bequia has an airport a short taxi from the property, which sits one mile from the main dock.",
        "related_sops": ["FF-101"],
        "search_keywords": ["ferry", "boat", "barbados", "st lucia", "saint lucia", "st vincent", "airport", "flight", "arrival", "dock", "getting here", "transfer"],
        "quiz": [{"question": "Is there a ferry from Barbados to Bequia?", "answer": "No — there is no ferry from Barbados or Saint Lucia."}],
        "category_tags": ["arrival", "transport"], "priority": "critical",
        "source": "faqs, home", **_UNCONFIRMED,
    },
    {
        "sop_id": "FF-605", "department": "Guest FAQ",
        "title": "Tipping & Gratuities",
        "purpose": "Give one consistent answer to a question guests are often uncomfortable asking.",
        "business_outcome": "Removes guest awkwardness and staff inconsistency on gratuities.",
        "scope": "All tipping questions.",
        "roles_responsible": ["Reception", "Restaurant"],
        "procedure": [
            "Tipping is not required at Firefly.",
            "Tips are gratefully accepted when offered.",
            "Never solicit a tip, and never imply that one is expected.",
        ],
        "escalation_rules": ["Any guest complaint about a gratuity goes to the owner/manager."],
        "quality_standards": ["The answer is identical from every staff member and every channel."],
        "kpis": ["Gratuity complaints (target zero)"],
        "common_mistakes": ["Suggesting a percentage, which the property has not published."],
        "ai_summary": "Tipping is not required but is gratefully accepted; no percentage is suggested and a tip is never solicited.",
        "related_sops": ["FF-303"],
        "search_keywords": ["tip", "tipping", "gratuity", "service charge", "expected"],
        "quiz": [{"question": "Is tipping required?", "answer": "No — it is not required, but it is gratefully accepted."}],
        "category_tags": ["guest", "finance"], "priority": "standard",
        "source": "faqs", **_UNCONFIRMED,
    },
    # ============================ STAFF OPERATIONS ============================
    {
        "sop_id": "FF-701", "department": "Staff Operations",
        "title": "Single-Channel Enquiry Handling (Tel/WhatsApp + Email)",
        "purpose": "Document how every inbound enquiry currently reaches the property, so the load can be measured and then relieved.",
        "business_outcome": "Every revenue line — rooms, restaurant, tours, golf, activities, villa — converges on one handset. Making that visible is the first step to relieving it.",
        "scope": "All inbound guest and enquiry traffic on every revenue line.",
        "roles_responsible": ["Owner/Manager"],
        "required_systems": ["WhatsApp", "Email"],
        "procedure": [
            "Room reservations arrive by Tel/WhatsApp on 1 784 532 5134 and by email to FireflyEstateBequia@gmail.com.",
            "Restaurant reservations — booking a table — arrive on the same Tel/WhatsApp number, 1 784 532 5134.",
            "Estate tours and activities arrive on the same number and the same email address.",
            "Golf tee times arrive on the same WhatsApp number.",
            "One WhatsApp number and one email address are therefore the entire inbound funnel for rooms, restaurant, tours, golf and activities.",
            "Log which revenue line each enquiry belongs to, so repeat questions can be identified and answered from the knowledge base instead of by a person.",
        ],
        "decision_tree": [
            {"condition": "an enquiry is fully answered by a published fact in this knowledge base", "action": "answer it directly with the citation, and log that it did not need the owner"},
            {"condition": "an enquiry needs a rate, a check-in time, a restaurant hour, a transfer price, or a villa service commitment", "action": "route it to the owner/manager — these are documented gaps, not facts (G1–G8)"},
        ],
        "escalation_rules": ["Anything touching money, a commitment, or a guest's arrival plan routes to the owner/manager."],
        "quality_standards": ["Every enquiry is tagged to a revenue line.", "No answer is given that is not backed by a cited fact."],
        "kpis": ["Enquiries answered without reaching the owner", "Enquiries per revenue line per week", "Median first-response time"],
        "common_mistakes": ["Answering from memory rather than from a cited fact, which is how inconsistency enters a small property."],
        "ai_summary": "To book a table, a room, a tour or golf the number is 1 784 532 5134 — rooms, restaurant, tours, golf and activities all arrive through that one Tel/WhatsApp number and one email address — the single funnel this system exists to relieve. Answer from cited facts; route gaps to the owner.",
        "related_sops": ["FF-204", "FF-401", "FF-501", "FF-503"],
        "search_keywords": ["whatsapp", "enquiry", "contact", "phone number", "number", "telephone", "email", "book a table", "table booking", "booking channel", "reservations", "funnel", "message"],
        "quiz": [{"question": "How many inbound channels serve all of Firefly's revenue lines?", "answer": "One WhatsApp/telephone number and one email address."}],
        "category_tags": ["operations", "revenue"], "priority": "critical",
        "source": "contact-us, eating-drinking, golf, plantation-tours", **_UNCONFIRMED,
    },
    {
        "sop_id": "FF-901", "department": "Staff Operations",
        "title": "Property Character & Tone of Voice ('Truthful Asides')",
        "purpose": "Define how Firefly speaks, so any assistant deployed here sounds like the property and not like a hotel chatbot.",
        "business_outcome": "Tone is the property's brand. An assistant that sounds wrong damages a small property more than one that answers slowly.",
        "scope": "Every guest-facing message, in any channel, from staff or from an agent.",
        "roles_responsible": ["Owner/Manager"],
        "procedure": [
            "Firefly publishes its own candour page and has deliberately chosen candour over polish.",
            "Disclose plainly: there are steep steps up to the main room building and down to the pool; the bar and lounge areas are relatively flat.",
            "Disclose plainly: two dogs (Hope and Duke), several cats and goats live on the estate.",
            "Describe the atmosphere as a relaxed and friendly house party; families are welcome.",
            "The property describes itself as not for the boring, the pretentious or the stuffy — match that register: warm, plain, a little wry.",
            "Never adopt corporate hotel language, and never smooth over a physical drawback the property itself discloses.",
        ],
        "decision_tree": [
            {"condition": "a draft guest message sounds like a corporate hotel chatbot", "action": "rewrite it in the property's own plain, warm, slightly wry register before it is sent"},
        ],
        "escalation_rules": ["Any message that would soften or omit a disclosed drawback is rewritten before sending."],
        "quality_standards": ["Physical drawbacks are disclosed, never hidden.", "Tone matches the property's own published voice."],
        "kpis": ["Guest surprise at arrival (target zero)", "Tone corrections needed before sending"],
        "common_mistakes": ["Writing polished hotel-marketing language that the property has explicitly rejected."],
        "ai_summary": "Firefly chose candour over polish: steep steps are disclosed, the dogs, cats and goats are disclosed, the atmosphere is a relaxed house party, and the voice is warm, plain and a little wry — never corporate.",
        "related_sops": ["FF-602", "FF-601"],
        "search_keywords": ["tone", "voice", "character", "candour", "truthful", "steps", "steep", "atmosphere", "house party", "families", "style"],
        "quiz": [{"question": "How does Firefly describe its own atmosphere?", "answer": "A relaxed and friendly house party — not for the boring, the pretentious or the stuffy."}],
        "category_tags": ["operations", "brand"], "priority": "high",
        "source": "truthful-asides", **_UNCONFIRMED,
    },
]

FIREFLY_SOPS: list[SOP] = [SOP.from_dict(d) for d in _RAW]


# ---------------------------------------------------------------------------
# Known gaps — deliberately NOT in the corpus, so the guardrail refuses them.
# Each is a question the discovery call must answer before an agent may speak to it.
# ---------------------------------------------------------------------------
FIREFLY_GAPS: list[dict] = [
    {"gid": "G1", "gap": "No published room rates",
     "terms": ["rate", "rates", "price", "cost", "how much", "nightly", "per night", "tariff", "quote"],
     "topic": ["room", "rooms", "stay", "night", "nights", "week", "cottage", "villa", "suite"],
     "blocks": "The assistant cannot quote a price; every rate question must route to a human.",
     "needed_from_operator": "Rate card by room type and season"},
    {"gid": "G2", "gap": "No published restaurant hours or menu",
     "terms": ["hours", "open", "opening", "close", "closing", "serve", "served", "service", "menu", "dishes", "what time"],
     "topic": ["restaurant", "dinner", "lunch", "breakfast", "bar", "kitchen", "food", "eat", "menu"],
     "blocks": "The highest-frequency guest question cannot be answered by any agent.",
     "needed_from_operator": "Service times per day and a current menu"},
    {"gid": "G3", "gap": "No published check-in / check-out times",
     "terms": ["what time", "time", "when", "hours", "earliest", "latest"],
     "topic": ["check in", "check-in", "checkin", "check out", "check-out", "checkout", "arrival time", "departure time"],
     "blocks": "A basic pre-arrival question is currently unanswerable.",
     "needed_from_operator": "Check-in and check-out times, and the early/late policy"},
    {"gid": "G4", "gap": "No airport or dock transfer detail or price",
     "terms": ["price", "cost", "how much", "fare", "book", "arrange", "time", "schedule", "meet"],
     "topic": ["taxi", "transfer", "pickup", "pick up", "airport", "dock", "ferry time", "shuttle", "collect"],
     "blocks": "The first-touch guest need arrives by WhatsApp every single time.",
     "needed_from_operator": "Transfer options, who provides them, and prices"},
    {"gid": "G5", "gap": "No day-pass or non-resident facility policy",
     "terms": ["use", "access", "allowed", "included", "may"],
     "topic": ["day pass", "day-pass", "day visitor", "facilities as a non-resident", "pool as a non-resident"],
     "blocks": "The restaurant welcomes non-residents, but whether they may use the pool is unknown.",
     "needed_from_operator": "What non-resident diners may and may not use"},
    {"gid": "G6", "gap": "No children, pet or accessibility policy beyond the candour page",
     "terms": ["policy", "allowed", "can i bring", "accept", "minimum age", "wheelchair", "accessible"],
     "topic": ["pet", "pets", "dog policy", "child policy", "age limit", "wheelchair", "disabled", "accessibility", "mobility"],
     "blocks": "No agent may answer a family, pet or mobility enquiry.",
     "needed_from_operator": "Child, pet and accessibility positions"},
    {"gid": "G7", "gap": "Villa service-request path undocumented",
     "terms": ["how long", "turnaround", "response time", "who handles", "process", "raise a request", "sla"],
     "topic": ["villa request", "villa service", "provisioning", "villa housekeeping"],
     "blocks": "The clearest agentic workflow on the property has no written process to automate.",
     "needed_from_operator": "How a villa request is raised, owned and closed today"},
    {"gid": "G8", "gap": "No cancellation window for restaurant or tour bookings",
     "terms": ["how long", "notice", "window", "deadline", "how far in advance", "cancel"],
     "topic": ["table", "tour booking", "reservation notice", "restaurant cancellation"],
     "blocks": "Confirmations and reminders cannot be automated.",
     "needed_from_operator": "Notice periods for tables and tours"},
    {"gid": "G9", "gap": "TripAdvisor rating unverified",
     "terms": ["rating", "reviews", "score", "stars", "rated"],
     "topic": ["tripadvisor", "trip advisor", "google review", "booking.com"],
     "blocks": "A rating cited from a secondary source must not enter a deck or an agent answer.",
     "needed_from_operator": "Confirm the current rating and review count directly"},
    {"gid": "G11", "gap": "No documented maintenance or safety-reporting procedure",
     "terms": [], "topic": [],
     "blocks": "The Work Order agent can prioritise and route a ticket, but it has no "
               "Firefly maintenance standard to cite — so its routing grounds on the "
               "nearest related record instead of a governing procedure.",
     "needed_from_operator": "How a defect is reported, who owns it, and what counts as urgent"},
    {"gid": "G10", "gap": "Yoga, pool, weddings and hiking pages not yet harvested",
     "terms": [],
     "topic": [],
     "blocks": "Minor — completes the seed before the confirmed KB load.",
     "needed_from_operator": "Nothing; Velocity completes this"},
]


def firefly_departments() -> list[str]:
    seen: list[str] = []
    for s in FIREFLY_SOPS:
        if s.department not in seen:
            seen.append(s.department)
    return seen


def confirmed_count() -> tuple[int, int]:
    """(operator_confirmed, total) — the provenance headline shown in the console."""
    confirmed = sum(1 for s in FIREFLY_SOPS if s.confidence == "operator_confirmed")
    return confirmed, len(FIREFLY_SOPS)
