"""7 - Executive Intelligence Agent (LLM-synthesized).

Aggregates the day's operational alerts (risks, staffing, revenue, compliance)
across one or many properties AND what the other agents actually did this cycle,
then produces a crisp executive briefing for the GM/owner. The briefing is
generated by the configured AI provider with an offline deterministic fallback,
and the raw structured alerts are attached for drill-down.

This is the *report* phase of the execution loop: it runs after the operational
agents and is handed a ``cycle_activity`` summary by the loop, so the GM's briefing
reflects the actions the system just took and what is waiting on a human approval —
which is what makes the loop actually close.
"""
from __future__ import annotations

from velocity_hos.llm import LLM, get_llm

from .base import Agent, Context, Recommendation, RiskLevel

_INSTRUCTION = "Write today's executive briefing for the General Manager."
_SECTIONS = ("risks", "staffing_alerts", "revenue_alerts", "compliance_alerts")

# Labels for the "what the system did this cycle" block folded in from the loop.
_ACTIVITY_LABELS = {
    "awaiting_your_approval": "awaiting_your_approval",
    "actions_auto_executed": "actions_taken",
    "answered_for_staff": "staff_questions_answered",
}


class ExecutiveIntelligenceAgent(Agent):
    name = "executive_intelligence"
    phase = "report"  # runs last; sees this cycle's activity

    def __init__(self, llm: LLM | None = None):
        self._llm = llm or get_llm()

    def evaluate(self, ctx: Context) -> list[Recommendation]:
        signals = ctx.inputs.get("signals", {})
        sections = {key: list(signals.get(key, [])) for key in _SECTIONS}

        # Fold in what the operational agents did this cycle (loop coordination).
        activity = ctx.inputs.get("cycle_activity", {})
        for src_key, label in _ACTIVITY_LABELS.items():
            items = list(activity.get(src_key, []))
            if items:
                sections[label] = items

        briefing = self._llm.summarize(_INSTRUCTION, sections)

        return [Recommendation(
            agent=self.name,
            summary=briefing,
            risk=RiskLevel.INFO,  # informational; drives human attention, not actions
            proposed_action={"type": "briefing", "tenant": ctx.tenant_id,
                             "sections": sections},
            rationale="Daily roll-up synthesized from operational alerts and this "
                      "cycle's agent activity (actions taken + items awaiting approval).",
        )]
