"""7 - Executive Intelligence Agent (LLM-synthesized).

Aggregates the day's operational alerts (risks, staffing, revenue, compliance)
across one or many properties and produces a crisp executive briefing for the
GM/owner. The briefing is generated by the LLM (Bedrock Claude) with an offline
deterministic fallback, and the raw structured alerts are attached for drill-down.
"""
from __future__ import annotations

from velocity_hos.llm import LLM, get_llm

from .base import Agent, Context, Recommendation, RiskLevel

_INSTRUCTION = "Write today's executive briefing for the General Manager."
_SECTIONS = ("risks", "staffing_alerts", "revenue_alerts", "compliance_alerts")


class ExecutiveIntelligenceAgent(Agent):
    name = "executive_intelligence"

    def __init__(self, llm: LLM | None = None):
        self._llm = llm or get_llm()

    def evaluate(self, ctx: Context) -> list[Recommendation]:
        signals = ctx.inputs.get("signals", {})
        sections = {key: list(signals.get(key, [])) for key in _SECTIONS}

        briefing = self._llm.summarize(_INSTRUCTION, sections)

        return [Recommendation(
            agent=self.name,
            summary=briefing,
            risk=RiskLevel.INFO,  # informational; drives human attention, not actions
            proposed_action={"type": "briefing", "tenant": ctx.tenant_id,
                             "sections": sections},
            rationale="Daily cross-property roll-up synthesized from operational alerts.",
        )]
